# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Nov  7 03:51:10 2021
# ------------------------------------------------

package:
  name: pycparser
  version: '2.21'
source:
  fn: pycparser-2.21.tar.gz
  sha256: e644fdec12f7872f86c58ff790da456218b10f863970249516d60a5eaca77206
  url: https://pypi.io/packages/source/p/pycparser/pycparser-2.21.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vvv && cp -r utils ${SP_DIR}/pycparser
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.10.8 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h9c3ff4c_4
    - libgcc-ng 11.2.0 h1d223b6_11
    - libgomp 11.2.0 h1d223b6_11
    - libnsl 2.0.0 h7f98852_0
    - libstdcxx-ng 11.2.0 he4da1e4_11
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.11 h36c2ea0_1013
    - ncurses 6.2 h58526e2_4
    - openssl 3.0.0 h7f98852_2
    - pip 21.3.1 pyhd8ed1ab_0
    - python 3.10.0 h543edf9_2_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h46c0cb4_0
    - setuptools 58.5.3 py310hff52083_0
    - sqlite 3.36.0 h9cd32fc_2
    - tk 8.6.11 h27826a3_1
    - tzdata 2021e he74cb21_0
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h36c2ea0_1013
  run:
    - python =2.7|>=3.4
test:
  imports:
    - pycparser
    - pycparser.ply
about:
  description: 'pycparser is a complete parser of the C language, written in pure
    Python using the PLY parsing library.

    It parses C code into an AST and can serve as a front-end for C compilers or analysis
    tools.

    '
  dev_url: https://github.com/eliben/pycparser
  home: https://github.com/eliben/pycparser
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Complete C99 parser in pure Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - scopatz
    - synapticarbors
