# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jan 29 22:53:02 2022
# ------------------------------------------------

package:
  name: pyopenssl
  version: 22.0.0
source:
  sha256: 660b1b1425aac4a1bea1d94168a85d99f0b3144c869dd4390d27629d0087f1bf
  url: https://pypi.io/packages/source/p/pyOpenSSL/pyOpenSSL-22.0.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pyopenssl_1643496850550/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vvv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.10.8 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_12
    - libgomp 11.2.0 h1d223b6_12
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.11 h36c2ea0_1013
    - ncurses 6.3 h9c3ff4c_0
    - openssl 3.0.0 h7f98852_2
    - pip 21.3.1 pyhd8ed1ab_0
    - python 3.10.2 hc74c709_1_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h46c0cb4_0
    - setuptools 60.5.0 py310hff52083_0
    - sqlite 3.37.0 h9cd32fc_0
    - tk 8.6.11 h27826a3_1
    - tzdata 2021e he74cb21_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h36c2ea0_1013
  run:
    - cryptography >=35.0
    - python >=3.6
test:
  imports:
    - OpenSSL
    - OpenSSL.SSL
    - OpenSSL.crypto
    - OpenSSL.rand
about:
  description: 'pyOpenSSL is a high-level wrapper around a subset of the OpenSSL library.

    It includes:

    -SSL.Connection objects, wrapping the methods of Python''s portable sockets

    -Callbacks written in Python

    -Extensive error-handling mechanism, mirroring OpenSSL''s error codes

    and much more.

    '
  dev_url: https://github.com/pyca/pyopenssl
  doc_source_url: https://github.com/pyca/pyopenssl/blob/master/doc/index.rst
  doc_url: https://pyopenssl.readthedocs.org/en/stable/
  home: https://github.com/pyca/pyopenssl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper module around the OpenSSL library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - goanpeca
    - nehaljwani
