CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
build_platform: osx-64
c_compiler: clang
c_compiler_version: '13'
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
cxx_compiler_version: '13'
extend_keys:
- ignore_version
- ignore_build_only_deps
- pin_run_as_build
- extend_keys
ffmpeg: '4.4'
fortran_compiler: gfortran
freetype: '2'
glib: '2'
harfbuzz: '4'
hdf5: 1.12.1
ignore_build_only_deps:
- numpy
- python
jasper: '2'
jpeg: '9'
libcblas: 3.9 *netlib
liblapack: 3.9 *netlib
liblapacke: 3.9 *netlib
libpng: '1.6'
libprotobuf: '3.20'
libtiff: '4'
libwebp: '1'
lua: '5'
macos_machine: arm64-apple-darwin20.0.0
numpy: '1.19'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  freetype:
    max_pin: x
  harfbuzz:
    max_pin: x
  jasper:
    max_pin: x
  jpeg:
    max_pin: x
  libpng:
    max_pin: x.x
  libtiff:
    max_pin: x
  zlib:
    max_pin: x.x
python: 3.8.* *_cpython
r_base: '3.5'
target_platform: osx-arm64
zip_keys:
- - python
  - numpy
- - c_compiler_version
  - cxx_compiler_version
zlib: '1.2'
