# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jul 23 12:03:23 2021
# ------------------------------------------------

package:
  name: libidn2
  version: 2.3.2
source:
  sha256: 76940cd4e778e8093579a9d195b25fff5e936e9dc6242068528b437a76764f91
  url: https://ftp.gnu.org/gnu/libidn/libidn2-2.3.2.tar.gz
build:
  number: '0'
  run_exports:
    - libidn2 >=2,<3.0a0
  string: h3422bc3_0
requirements:
  build:
    - cctools_osx-64 949.0.1 h6407bdd_22
    - cctools_osx-arm64 949.0.1 h55de48a_22
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_2
    - clangxx 11.1.0 default_he082bbe_1
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h7660a38_2
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_0
    - libiconv 1.16 haf1e3a3_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_0
    - llvm-tools 11.1.0 hd011deb_2
    - make 4.3 h22f3db7_1
    - pkg-config 0.29.2 h31203cd_1008
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h7795811_1010
  host:
    - gettext 0.19.8.1 hea66d9f_1005
    - libcxx 12.0.1 h168391b_0
    - libffi 3.3 h9f76cd9_2
    - libiconv 1.16 h642e427_0
    - libunistring 0.9.10 h3422bc3_0
  run:
    - gettext >=0.19.8.1,<1.0a0
    - libunistring >=0,<1.0a0
test:
  commands:
    - test -f "${PREFIX}/include/idn2.h"
    - test -f "${PREFIX}/lib/libidn2${SHLIB_EXT}"
about:
  home: https://www.gnu.org/software/libidn/#libidn2
  license: LGPLv2
  license_file: COPYING
  summary: Library for internationalized domain names (IDNA2008) support
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hmaarrfk
