# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jan  7 18:28:56 2022
# ------------------------------------------------

package:
  name: requests
  version: 2.27.1
source:
  sha256: 68d7c56fd5a8999887728ef304a6d12edc7be74f1cfa47714fc8b414525c9a61
  url: https://pypi.io/packages/source/r/requests/requests-2.27.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/requests_1641580202195/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.10.8 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_11
    - libgomp 11.2.0 h1d223b6_11
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.11 h36c2ea0_1013
    - ncurses 6.2 h58526e2_4
    - openssl 3.0.0 h7f98852_2
    - pip 21.3.1 pyhd8ed1ab_0
    - python 3.10.1 h543edf9_2_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h46c0cb4_0
    - setuptools 60.2.0 py310hff52083_0
    - sqlite 3.37.0 h9cd32fc_0
    - tk 8.6.11 h27826a3_1
    - tzdata 2021e he74cb21_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h36c2ea0_1013
  run:
    - certifi >=2017.4.17
    - charset-normalizer >=2.0.0,<2.1
    - idna >=2.5,<4
    - python >=3.6
    - urllib3 >=1.21.1,<1.27
test:
  commands:
    - pip check
  imports:
    - requests
  requires:
    - pip
about:
  dev_url: https://github.com/psf/requests
  home: http://python-requests.org
  license: Apache-2.0
  license_file: LICENSE
  summary: "Requests is an elegant and simple HTTP library for Python, built with\
    \ \u2665."
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - sigmavirus24
