# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Oct 31 16:53:51 2020
# ------------------------------------------------

package:
    name: libpng
    version: 1.6.37
source:
    patches:
        - 0001-Include-pkg-config-files-in-the-Windows-packages-too.patch
    sha256: daeb2620d829575513e35fecc83f0d3791a620b9b93d800b763542ece9390fb4
    url: http://download.sourceforge.net/libpng/libpng-1.6.37.tar.gz
build:
    number: '2'
    run_exports:
        - libpng >=1.6.37,<1.7.0a0
    string: hf7e6567_2
requirements:
    build:
        - autoconf 2.69 pl526h1de35cc_9
        - automake 1.16.2 pl526_1
        - cctools_osx-arm64 949.0.1 h1c9b417_16
        - clang 11.0.0 1
        - clang-11 11.0.0 default_h000dee7_1
        - clang_osx-arm64 11.0.0 hd8ecd2b_2
        - clangxx 11.0.0 default_hf57f61e_1
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - ld64_osx-64 530 h66d9e41_16
        - ld64_osx-arm64 530 h8c8ad8c_16
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h000dee7_1
        - libcxx 11.0.0 h439d374_0
        - libllvm11 11.0.0 hf85e3d2_0
        - libtool 2.4.6 hf1706ab_1006
        - llvm-tools 11.0.0 hf85e3d2_0
        - m4 1.4.18 haf1e3a3_1001
        - make 4.3 h22f3db7_1
        - perl 5.26.2 hbcb3906_1008
        - tapi 1100.0.11 h9ce4665_0
        - zlib 1.2.11 h7795811_1010
    host:
        - zlib 1.2.11 h31e879b_1009
    run:
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libpng.a
        - test -f ${PREFIX}/lib/libpng${SHLIB_EXT}
        - libpng-config --version
about:
    description: 'libpng is the official PNG reference library. It supports almost
        all PNG

        features, is extensible, and has been extensively tested for over 20 years.

        '
    dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
    doc_url: http://www.libpng.org/pub/png/libpng.html
    home: http://www.libpng.org/pub/png/libpng.html
    license: zlib/libpng
    license_file: LICENSE
    license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
    summary: PNG reference library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - pkgw
