# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: hdf5
  version: 1.12.1
source:
  patches:
    - patches/osx_cross_configure.patch
    - patches/osx_cross_fortran_src_makefile.patch
    - patches/osx_cross_hl_fortran_src_makefile.patch
    - patches/osx_cross_src_makefile.patch
    - patches/test_Makefile.in.patch
    - patches/testpar_Makefile.in.patch
  sha256: 79c66ff67e666665369396e9c90b32e238e501f345afd2234186bfb8331081ca
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.1/src/hdf5-1.12.1.tar.gz
build:
  number: 104
  run_exports:
    - hdf5 >=1.12.1,<1.12.2.0a0
  string: nompi_hd9dbc9e_104
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h609b070_9
    - cctools_osx-arm64 973.0.1 h7ef2fa9_9
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_7
    - clangxx 12.0.1 default_he082bbe_4
    - clangxx_osx-arm64 12.0.1 h2ae1534_7
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - gfortran_impl_osx-64 9.3.0 h9cc0e5e_23
    - gfortran_impl_osx-arm64 11.0.1.dev0 h3653101_23
    - gfortran_osx-arm64 11.0.1.dev0 h64a2375_15
    - gmp 6.2.1 h2e338ed_0
    - isl 0.22.1 hb1e8313_2
    - ld64_osx-64 609 hc6b1d1e_9
    - ld64_osx-arm64 609 hf6d2360_9
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 12.0.1 habf9029_1
    - libgfortran-devel_osx-64 9.3.0 h6c81a4c_23
    - libgfortran-devel_osx-arm64 11.0.1.dev0 hf114ba7_23
    - libgfortran5 9.3.0 h6c81a4c_23
    - libiconv 1.16 haf1e3a3_0
    - libllvm12 12.0.1 hd011deb_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h9173be1_1013
    - llvm-openmp 13.0.1 hcb1a161_1
    - llvm-tools 12.0.1 hd011deb_2
    - make 4.3 h22f3db7_1
    - mpc 1.2.1 hbb51d92_0
    - mpfr 4.1.0 h0f52abe_1
    - openssl 3.0.0 h0d85af4_2
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h9173be1_1013
  host:
    - c-ares 1.18.1 h3422bc3_0
    - ca-certificates 2021.10.8 h4653dfc_0
    - krb5 1.19.2 he492e65_4
    - libcurl 7.81.0 h8d07098_0
    - libcxx 12.0.1 h168391b_1
    - libedit 3.1.20191231 hc8eb9b7_2
    - libev 4.33 h642e427_1
    - libgfortran 5.0.0.dev0 11_0_1_hf114ba7_23
    - libgfortran5 11.0.1.dev0 hf114ba7_23
    - libnghttp2 1.47.0 hf30690b_0
    - libssh2 1.10.0 h7a5bd25_2
    - libzlib 1.2.11 hee7b306_1013
    - llvm-openmp 13.0.1 h455960f_1
    - ncurses 6.3 hc470f4d_0
    - openssl 3.0.0 h3422bc3_2
    - zlib 1.2.11 hee7b306_1013
  run:
    - libcurl >=7.81.0,<8.0a0
    - libcurl >=7.81.0,<8.0a0
    - libcxx >=12.0.1
    - libgfortran 5.*
    - libgfortran5 >=11.0.1.dev0
    - libzlib >=1.2.11,<1.3.0a0
    - openssl >=3.0.0,<4.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - command -v h5c++
    - command -v h5cc
    - command -v h5fc
    - command -v h5redeploy
    - command -v gif2h5
    - command -v h52gif
    - command -v h5copy
    - command -v h5debug
    - command -v h5diff
    - command -v h5dump
    - command -v h5import
    - command -v h5jam
    - command -v h5ls
    - command -v h5mkgrp
    - command -v h5repack
    - command -v h5repart
    - command -v h5stat
    - command -v h5unjam
    - test -f $PREFIX/lib/libhdf5${SHLIB_EXT}
    - test -f $PREFIX/lib/libhdf5_cpp${SHLIB_EXT}
    - test -f $PREFIX/lib/libhdf5_hl${SHLIB_EXT}
    - test -f $PREFIX/lib/libhdf5_hl_cpp${SHLIB_EXT}
    - h5dump --filedriver=ros3 "http://s3.amazonaws.com/hdfgroup/data/hdf5demo/tall.h5"
      | grep '^HDF5'
  files:
    - compound_fortran2003.f90
    - h5_cmprss.c
    - h5_cmprss.f90
    - h5tutr_cmprss.cpp
  requires:
    - clang_osx-arm64 12.*
    - clangxx_osx-arm64 12.*
    - gfortran_osx-arm64 11.*
    - pkg-config
about:
  dev_url: https://github.com/HDFGroup/hdf5
  doc_url: https://portal.hdfgroup.org/display/HDF5/HDF5
  home: http://www.hdfgroup.org/HDF5/
  license: LicenseRef-HDF5
  license_family: BSD
  license_file: COPYING
  summary: HDF5 is a data model, library, and file format for storing and managing
    data
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - astrofrog-conda-forge
    - davidbrochart
    - gillins
    - groutr
    - hmaarrfk
    - jakirkham
    - marcelotrevisani
    - marqh
    - ocefpaf
    - scopatz
    - varlackc
