# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Apr 18 12:43:17 2022
# ------------------------------------------------

package:
  name: jpeg
  version: 9e
source:
  patches: null
  sha256: 4077d6a6a75aeb01884f708919d25934c93305e49f7e3f36db9129320e6f4f3d
  url: http://www.ijg.org/files/jpegsrc.v9e.tar.gz
build:
  number: '1'
  run_exports:
    - jpeg >=9e,<10a
  string: h1c322ee_1
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_8
    - clangxx 12.0.1 default_he082bbe_4
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - ld64_osx-64 609 hc6b1d1e_10
    - ld64_osx-arm64 609 hf6d2360_10
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 13.0.1 hc203e6f_0
    - libllvm12 12.0.1 hd011deb_2
    - libllvm13 13.0.1 h64f94b2_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-tools 12.0.1 hd011deb_2
    - make 4.3 h22f3db7_1
    - openssl 3.0.2 h6c3fc93_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h6c3fc93_1014
  run: []
test:
  commands:
    - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg
  files:
    - testorig.jpg
about:
  home: http://www.ijg.org/
  license: IJG
  license_file: /Users/runner/work/1/s/recipe/LICENSE.txt
  summary: read/write jpeg COM, EXIF, IPTC medata
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - gillins
    - jakirkham
    - msarahan
    - ocefpaf
