# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Oct 27 16:37:41 2021
# ------------------------------------------------

package:
  name: c-ares
  version: 1.18.1
source:
  sha256: 1a7d52a8a84a9fbffb1be9133c0f6e17217d91ea5a6fa61f6b4729cda78ebbcf
  url: https://c-ares.haxx.se/download/c-ares-1.18.1.tar.gz
build:
  number: '0'
  run_exports:
    - c-ares >=1.18.1,<2.0a0
  string: h3422bc3_0
requirements:
  build:
    - cctools_osx-64 949.0.1 h6407bdd_23
    - cctools_osx-arm64 949.0.1 h55de48a_23
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_3
    - clangxx 11.1.0 default_he082bbe_1
    - cmake-no-system 3.16.5 he49afe7_0
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h6a69015_3
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_2
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 11.1.0 hd011deb_2
    - ninja 1.10.2 h940c156_1
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h9173be1_1013
  run: []
  run_constraint:
    - c-ares-static <0a0
about:
  home: https://c-ares.haxx.se/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
