# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Apr 22 07:24:27 2022
# ------------------------------------------------

package:
  name: libprotobuf
  version: 3.20.1
source:
  - patches: null
    sha256: 8b28fdd45bab62d15db232ec404248901842e5340299a57765e48abe8a80d930
    url: https://github.com/protocolbuffers/protobuf/archive/v3.20.1/libprotobuf-v3.20.1.tar.gz
  - folder: third_party/benchmark
    sha256: 5dc92703f811f94e2aa63bdab07ab749f28a094befa6cdfd5fe177f947590a48
    url: https://github.com/google/benchmark/archive/5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8.tar.gz
  - folder: third_party/googletest
    sha256: 0e2f36e8e403c125fd0ab02171bdb786d3b6b3875b6ccf3b2eb7969be8faecd0
    url: https://github.com/google/googletest/archive/5ec7f0c4a113e2f18ac2c6cc7df51ad6afc24081.tar.gz
build:
  number: '0'
  run_exports:
    - libprotobuf >=3.20.1,<3.21.0a0
  string: h332123e_0
requirements:
  build:
    - autoconf 2.69 pl5321hc0e15e3_11
    - automake 1.16.5 pl5321h694c41f_0
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_0
    - clangxx 13.0.1 default_he082bbe_0
    - clangxx_osx-arm64 13.0.1 hdeb254d_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - ld64_osx-64 609 hd77a64a_10
    - ld64_osx-arm64 609 hfeae783_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 13.0.1 hc203e6f_0
    - libiconv 1.16 haf1e3a3_0
    - libllvm13 13.0.1 h64f94b2_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-tools 13.0.1 h64f94b2_2
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - openssl 3.0.2 h6c3fc93_1
    - perl 5.32.1 2_h0d85af4_perl5
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - unzip 6.0 h0d85af4_3
  host:
    - libcxx 13.0.1 h6a5c8ee_0
    - libzlib 1.2.11 h90dfc92_1014
    - zlib 1.2.11 h90dfc92_1014
  run:
    - libcxx >=13.0.1
    - libzlib >=1.2.11,<1.3.0a0
    - zlib >=1.2.11,<1.3.0a0
about:
  description: 'Protocol buffers are Google''s language-neutral,

    platform-neutral, extensible mechanism for serializing structured data-

    think XML, but smaller, faster, and simpler.

    '
  doc_source_url: https://github.com/protocolbuffers/protobuf/releases
  doc_url: https://developers.google.com/protocol-buffers/
  home: https://developers.google.com/protocol-buffers/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Protocol Buffers - Google's data interchange format. C++ Libraries and
    protoc, the protobuf compiler.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dopplershift
    - h-vetinari
    - hajapy
    - jakirkham
    - ocefpaf
    - wesm
    - xhochy
