# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: libzlib
  version: 1.2.12
source:
  sha256: 91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9
  url: http://zlib.net/zlib-1.2.12.tar.gz
build:
  number: 0
  run_exports:
    - libzlib >=1.2.12,<1.3.0a0
  string: h90dfc92_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 12.0.1 hf840cc2_9
  run: []
  run_constrained:
    - zlib 1.2.12 *_0
test:
  commands:
    - test ! -f ${PREFIX}/lib/libz.a
    - test ! -f ${PREFIX}/lib/libz${SHLIB_EXT}
    - test ! -f ${PREFIX}/include/zlib.h
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: http://zlib.net/manual.html
  home: http://zlib.net/
  license: Zlib
  license_family: Other
  license_file: license.txt
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  feedstock-name: zlib
  final: true
  recipe-maintainers:
    - groutr
    - isuruf
    - msarahan
    - ocefpaf
