# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sun Mar  6 23:24:20 2022
# ------------------------------------------------

package:
  name: x265
  version: '3.5'
source:
  sha256: e70a3335cacacbba0b3a20ec6fecd6783932288ebc8163ad74bcc9606477cae8
  url: https://bitbucket.org/multicoreware/x265_git/downloads/x265_3.5.tar.gz
build:
  number: '3'
  run_exports:
    - x265 >=3.5,<3.6.0a0
  string: hbc6ce65_3
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.18.1 h0d85af4_0
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h609b070_9
    - cctools_osx-arm64 973.0.1 h7ef2fa9_9
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_7
    - clangxx 12.0.1 default_he082bbe_4
    - clangxx_osx-arm64 12.0.1 h2ae1534_7
    - cmake 3.22.3 h35a7dd9_0
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - expat 2.4.6 h96cf925_0
    - krb5 1.19.2 hb98e516_4
    - ld64_osx-64 609 hc6b1d1e_9
    - ld64_osx-arm64 609 hf6d2360_9
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcurl 7.81.0 h97da3c1_0
    - libcxx 12.0.1 habf9029_1
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libllvm12 12.0.1 hd011deb_2
    - libnghttp2 1.47.0 hca56917_0
    - libssh2 1.10.0 hd3787cc_2
    - libuv 1.43.0 h0d85af4_0
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 12.0.1 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - make 4.3 h22f3db7_1
    - nasm 2.15.05 h0d85af4_0
    - ncurses 6.3 he49afe7_0
    - openssl 3.0.0 h0d85af4_2
    - rhash 1.4.1 h35c211d_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
    - zstd 1.5.2 h582d3a0_0
  host:
    - libcxx 12.0.1 h168391b_1
  run:
    - libcxx >=12.0.1
test:
  commands:
    - test -f ${PREFIX}/lib/libx265${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libx265.a
    - test -f ${PREFIX}/lib/pkgconfig/x265.pc
    - test -f ${PREFIX}/include/x265.h
about:
  description: 'x265 is a H.265 / HEVC video encoder application library, designed
    to encode

    video or images into an H.265 / HEVC encoded bitstream.

    '
  dev_url: https://bitbucket.org/multicoreware/x265_git
  doc_url: https://x265.readthedocs.io/
  home: https://www.x265.org/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Open Source H.265/HEVC video encoder
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - matthiasdiener
