# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Jun 13 07:16:50 2022
# ------------------------------------------------

package:
  name: gnutls
  version: 3.7.6
source:
  patches:
    - correct_ssl_test.patch
  sha256: 77065719a345bfb18faa250134be4c53bef70c1bd61f6c0c23ceb8b44f0262ff
  url: https://www.gnupg.org/ftp/gcrypt/gnutls/v3.7/gnutls-3.7.6.tar.xz
build:
  ignore_run_exports:
    - gmp
  number: '5'
  run_exports:
    - gnutls >=3.7.6,<3.8.0a0
  string: h27a1928_5
requirements:
  build:
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_2
    - clangxx 13.0.1 default_he082bbe_0
    - clangxx_osx-arm64 13.0.1 hdeb254d_2
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.5 hce7ea42_1
    - libiconv 1.16 haf1e3a3_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.5 h41df66c_0
    - libzlib 1.2.12 h6c3fc93_0
    - llvm-tools 13.0.1 h64f94b2_2
    - make 4.3 h22f3db7_1
    - openssl 3.0.3 hfe4f2af_0
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - gettext 0.19.8.1 h049c9fb_1008
    - gmp 6.2.1 h9f76cd9_0
    - libcxx 14.0.5 h04bba0f_1
    - libffi 3.4.2 h3422bc3_5
    - libiconv 1.16 h642e427_0
    - libidn2 2.3.2 h3422bc3_0
    - libtasn1 4.18.0 he4db4b2_1
    - libunistring 0.9.10 h3422bc3_0
    - nettle 3.8 h63371fa_0
    - p11-kit 0.24.1 h29577a5_0
  run:
    - gettext >=0.19.8.1,<1.0a0
    - libcxx >=13.0.1
    - libidn2 >=2,<3.0a0
    - libtasn1 >=4.18.0,<5.0a0
    - nettle >=3.8,<3.9.0a0
    - p11-kit >=0.24.1,<0.25.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libgnutls${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libgnutlsxx${SHLIB_EXT}
about:
  dev_url: https://gitlab.com/gnutls/gnutls/tree/master
  doc_url: http://www.gnutls.org/documentation.html
  home: http://www.gnutls.org/index.html
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: GnuTLS is a secure communications library implementing the SSL, TLS and
    DTLS protocols
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - sachalau
    - scopatz
    - sdvillal
