# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sun Aug 16 06:54:50 2020
# ------------------------------------------------

package:
    name: libiconv
    version: '1.16'
source:
    sha256: e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04
    url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.16.tar.gz
build:
    number: '0'
    run_exports:
        - libiconv >=1.16,<2.0a0
    string: h642e427_0
requirements:
    build:
        - cctools_osx-arm64 949.0.1 ha30c52b_9
        - clang 11.0.0.rc1 default_hf57f61e_0
        - clang_osx-arm64 11.0.0.rc1 hd819f65_5
        - clangxx 11.0.0.rc1 default_hf57f61e_0
        - compiler-rt 11.0.0.rc1 h810911b_0
        - compiler-rt_osx-64 11.0.0.rc1 h2a69e3a_0
        - ld64_osx-arm64 530 h8c8ad8c_9
        - libclang-cpp11 11.0.0.rc1 default_hf57f61e_0
        - libcxx 11.0.0.rc1 h5f48129_0
        - libllvm11 11.0.0.rc1 h009f743_3
        - libtool 2.4.6 haf1e3a3_1003
        - llvm-tools 11.0.0.rc1 h1341992_3
        - make 4.3 h0b31af3_0
        - tapi 1100.0.11 h879752b_0
        - zlib 1.2.11 1007
test:
    commands:
        - iconv --help
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - conda inspect objects -p $PREFIX $PKG_NAME
about:
    home: https://www.gnu.org/software/libiconv/
    license: GPL and LGPL
    license_file: COPYING
    summary: Provides iconv for systems which don't have one (or that cannot convert
        from/to Unicode.)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jhamman
        - ocefpaf
        - scopatz
