# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Jul 22 11:47:31 2021
# ------------------------------------------------

package:
  name: libunistring
  version: 0.9.10
source:
  fn: libunistring-0.9.10.tar.xz
  sha256: eb8fb2c3e4b6e2d336608377050892b54c3c983b646c561836550863003c05d7
  url: http://ftpmirror.gnu.org/libunistring/libunistring-0.9.10.tar.xz
build:
  number: '0'
  run_exports:
    - libunistring >=0,<1.0a0
  string: h3422bc3_0
requirements:
  build:
    - cctools_osx-64 949.0.1 h6407bdd_22
    - cctools_osx-arm64 949.0.1 h55de48a_22
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_2
    - clangxx 11.1.0 default_he082bbe_1
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h7660a38_2
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_0
    - llvm-tools 11.1.0 hd011deb_2
    - make 4.3 h22f3db7_1
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h7795811_1010
  host: []
  run: []
test:
  commands:
    - test -e $PREFIX/lib/libunistring.a
    - test -e $PREFIX/lib/libunistring.dylib
about:
  home: https://www.gnu.org/software/libunistring
  license: GPL-3.0-only OR LGPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LIB
  summary: This library provides functions for manipulating Unicode strings and for
    manipulating C strings according to the Unicode standard.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bgruening
    - stefan-balke
