# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Jun  4 06:15:32 2022
# ------------------------------------------------

package:
  name: nettle
  version: '3.8'
source:
  fn: nettle-3.8.tar.gz
  sha256: 7576c68481c198f644b08c160d1a4850ba9449e308069455b5213319f234e8e6
  url: https://ftp.gnu.org/gnu/nettle/nettle-3.8.tar.gz
build:
  number: '0'
  run_exports:
    - nettle >=3.8,<3.9.0a0
  string: h63371fa_0
requirements:
  build:
    - autoconf 2.69 pl5321hc0e15e3_11
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_2
    - clangxx 13.0.1 default_he082bbe_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.4 hc203e6f_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.12 h6c3fc93_0
    - llvm-tools 13.0.1 h64f94b2_2
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - openssl 3.0.3 hfe4f2af_0
    - perl 5.32.1 2_h0d85af4_perl5
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  run: []
test:
  commands:
    - test -f ${PREFIX}/lib/libnettle${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libhogweed${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libnettle.a
    - test ! -f ${PREFIX}/lib/libhogweed.a
about:
  description: Nettle is a low-level cryptographic library that is designed to fit
    easily in more or less any context. In crypto toolkits for object-oriented languages
    (C++, Python, Pike, ...), in applications like LSH or GNUPG, or even in kernel
    space. Simple, fast, extensible JSON encoder/decoder for Python
  dev_url: https://git.lysator.liu.se/nettle/nettle
  doc_url: https://www.lysator.liu.se/~nisse/nettle/nettle.html
  home: https://www.lysator.liu.se/~nisse/nettle/
  license: GPL 2 and LGPL3
  license_family: GPL
  license_file: /Users/runner/work/1/s/recipe/LICENSE
  summary: Nettle is a low-level cryptographic library that is designed to fit easily
    in more or less any context
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - erykoff
    - sachalau
