# This file created by conda-build 3.21.9
# ------------------------------------------------

package:
  name: libblas
  version: 3.9.0
source:
  - patches:
      - patches/0001-Test-BLAS-and-LAPACKE-in-addition-to-LAPACK.patch
    sha256: 106087f1bb5f46afdfba7f569d0cbe23dacb9a07cd24733765a0e89dbe1ad573
    url: https://github.com/Reference-LAPACK/lapack/archive/v3.9.0.tar.gz
  - folder: vecLibFort
    sha256: 80de7c6e83d1d84d016b4cb299f2c15f5a82b9d36865dd5c16bf221fe9a303ad
    url: https://github.com/isuruf/vecLibFort/archive/99af8640e98c829b41c3235e3706760cd5696fe4.tar.gz
build:
  number: 15
  run_exports:
    - libblas >=3.9.0,<4.0a0
  string: 15_osxarm64_openblas
  track_features: null
requirements:
  host:
    - libgfortran 5.0.0.dev0 11_0_1_hf114ba7_23
    - libgfortran5 11.0.1.dev0 hf114ba7_23
    - libopenblas 0.3.20 openmp_h2209c59_0
    - llvm-openmp 14.0.4 hd125106_0
  run:
    - libopenblas >=0.3.20,<0.3.21.0a0
    - libopenblas >=0.3.20,<1.0a0
  run_constrained:
    - blas * openblas
    - libcblas 3.9.0 15_osxarm64_openblas
    - liblapack 3.9.0 15_osxarm64_openblas
    - liblapacke 3.9.0 15_osxarm64_openblas
test:
  commands:
    - test -f $PREFIX/lib/libblas.3.dylib
about:
  home: https://github.com/conda-forge/blas-feedstock
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
  summary: Metapackage to select the BLAS variant. Use conda's pinning mechanism in
    your environment to control which variant you want.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - h-vetinari
    - isuruf
    - jakirkham
    - ocefpaf
    - pelson
