# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Aug 12 05:06:42 2020
# ------------------------------------------------

package:
    name: xz
    version: 5.2.5
source:
    patches:
        - 0001-Add-vs2008-support-via-cmake.patch
        - 0002-Add-gettimeofday-for-VS2008.patch
    sha256: 5117f930900b341493827d63aa910ff5e011e0b994197c3b71c08a20228a42df
    url: http://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2
build:
    number: '1'
    run_exports:
        - xz >=5.2.5,<6.0a0
    string: h642e427_1
requirements:
    build:
        - autoconf 2.69 pl526h1de35cc_9
        - automake 1.16.2 pl526_1
        - cctools_osx-arm64 949.0.1 ha30c52b_6
        - clang 11.0.0.rc1 default_hf57f61e_0
        - clang_osx-arm64 11.0.0.rc1 hd819f65_4
        - clangxx 11.0.0.rc1 default_hf57f61e_0
        - compiler-rt 11.0.0.rc1 h810911b_0
        - compiler-rt_osx-64 11.0.0.rc1 h2a69e3a_0
        - libclang-cpp11 11.0.0.rc1 default_hf57f61e_0
        - libcxx 11.0.0.rc1 h5f48129_0
        - libllvm11 11.0.0.rc1 h009f743_3
        - libtool 2.4.6 haf1e3a3_1003
        - lld 11.0.0.rc1 ha82a7da_0
        - llvm-tools 11.0.0.rc1 h1341992_3
        - m4 1.4.18 h1de35cc_1001
        - make 4.3 h0b31af3_0
        - perl 5.26.2 haec8ef5_1006
        - zlib 1.2.11 1007
about:
    description: 'XZ Utils is free general-purpose data compression software with
        a high

        compression ratio. XZ Utils were written for POSIX-like systems, but also

        work on some not-so-POSIX systems.

        '
    dev_url: http://git.tukaani.org/
    doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
    doc_url: http://tukaani.org/xz/
    home: http://tukaani.org/xz/
    license: LGPL-2.1 and GPL-2.0
    license_file: COPYING
    summary: Data compression software with high compression ratio
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - msarahan
        - nehaljwani
        - ocefpaf
        - scopatz
