# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Jun 15 20:10:20 2022
# ------------------------------------------------

package:
  name: certifi
  version: 2022.6.15
source:
  - folder: certifi
    sha256: 84c85a9078b11105f04f3036a9482ae10e4621616db313fe045dd24743a0820d
    url: https://pypi.io/packages/source/c/certifi/certifi-2022.6.15.tar.gz
  - folder: pip_wheel
    sha256: 0f35d63b7245205f4060efe1982f5ea2196aa6e5b26c07669adcf800e2542026
    url: https://pypi.io/packages/py2.py3/p/pip/pip-20.2.3-py2.py3-none-any.whl
  - folder: setuptools_wheel
    sha256: 4dd5bb0a0a0cff77b46ca5dd3a84857ee48c83e8223886b556613c724994073f
    url: https://pypi.io/packages/py3/s/setuptools/setuptools-49.6.0-py3-none-any.whl
build:
  number: '0'
  string: py310hbe9552e_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 14.0.4 h694c41f_0
    - clang-14 14.0.4 default_h55ffa42_0
    - clang_osx-arm64 14.0.4 h4fe1f6c_2
    - clangxx 14.0.4 default_h55ffa42_0
    - compiler-rt 14.0.4 h7fcd477_0
    - compiler-rt_osx-64 14.0.4 h6df654d_0
    - cross-python_osx-arm64 3.10 23_cpython
    - crossenv 1.2.0 pyhd8ed1ab_7
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 609 h1e06c2b_10
    - ld64_osx-arm64 609 h52af8cb_10
    - libclang-cpp14 14.0.4 default_h55ffa42_0
    - libcxx 14.0.5 hce7ea42_1
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.16 haf1e3a3_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libzlib 1.2.12 h6c3fc93_0
    - llvm-tools 14.0.4 h41df66c_0
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.3 hfe4f2af_0
    - popt 1.16 h7b079dc_2002
    - python 3.10.5 hdd68b96_0_cpython
    - readline 8.1.2 h3899abd_0
    - rsync 3.2.3 h7841d2a_4
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.38.5 hd9f0692_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2022a h191b570_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.12 h6c3fc93_0
    - zstd 1.5.2 ha9df2e0_1
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.5.18.1 h4653dfc_0
    - libffi 3.4.2 h3422bc3_5
    - libzlib 1.2.12 ha287fd2_1
    - ncurses 6.3 h07bb92c_1
    - openssl 3.0.3 ha287fd2_0
    - python 3.10.5 h4eee789_0_cpython
    - readline 8.1.2 h46ed386_0
    - sqlite 3.38.5 h40dfcc0_0
    - tk 8.6.12 he1e0b03_0
    - tzdata 2022a h191b570_0
    - xz 5.2.5 h642e427_1
    - zlib 1.2.12 ha287fd2_1
  run:
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
test:
  imports:
    - certifi
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/certifi
  home: http://certifi.io/
  license: ISC
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
    - sigmavirus24
