# This file created by conda-build 3.21.3
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Jan 14 17:52:56 2021
# ------------------------------------------------

package:
  name: freetype
  version: 2.10.4
source:
  patches:
    - 0003-Install-the-pkg-config-file-on-Windows-too.patch
  sha256: 5eab795ebb23ac77001cfb68b7d4d50b5d6c7469247b0b01b2c953269f658dac
  url: http://download.savannah.gnu.org/releases/freetype/freetype-2.10.4.tar.gz
build:
  number: '1'
  run_exports:
    - freetype >=2.10.4,<3.0a0
  string: h17b34a0_1
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h9541561_19
    - clang 11.0.0 h694c41f_2
    - clang-11 11.0.0 default_h9e6edd0_2
    - clang_osx-arm64 11.0.0 h40be2b1_8
    - clangxx 11.0.0 default_h9e6edd0_2
    - compiler-rt 11.0.0 h01488ec_2
    - compiler-rt_osx-64 11.0.0 hd3c4e95_2
    - ld64_osx-64 530 hea264c1_19
    - ld64_osx-arm64 530 ha0a8365_19
    - ldid 2.1.2 h7660a38_2
    - libclang-cpp11 11.0.0 default_h9e6edd0_2
    - libcxx 11.0.0 h4c3b8ed_1
    - libllvm11 11.0.0 hf85e3d2_0
    - libtool 2.4.6 h2e338ed_1007
    - llvm-tools 11.0.0 hf85e3d2_0
    - make 4.3 h22f3db7_1
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h7795811_1010
  host:
    - libpng 1.6.37 hf7e6567_2
    - zlib 1.2.11 h31e879b_1009
  run:
    - libpng >=1.6.37,<1.7.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - ${PREFIX}/bin/freetype-config --version
about:
  description: 'FreeType is designed to be small, efficient, highly customizable

    and portable while capable of producing high-quality output (glyph images)

    of most vector and bitmap font formats.

    '
  dev_url: http://git.savannah.gnu.org/cgit/freetype/
  doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
  doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
  home: https://www.freetype.org/
  license: GPL-2.0-only and LicenseRef-FreeType
  license_file:
    - docs/FTL.TXT
    - docs/GPLv2.TXT
  summary: A Free, High-Quality, and Portable Font Engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
