# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Feb 24 18:31:54 2022
# ------------------------------------------------

package:
  name: aom
  version: 3.3.0
source:
  sha256: 1dafde32bc2237bf0570294661ae61db30e818840f77dc4e90d1ebf5a6286664
  url: https://storage.googleapis.com/aom-releases/libaom-3.3.0.tar.gz
build:
  number: '1'
  run_exports:
    - aom >=3.3.0,<3.4.0a0
  string: h07bb92c_1
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.18.1 h0d85af4_0
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h609b070_7
    - cctools_osx-arm64 973.0.1 hd1d4517_7
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_6
    - clangxx 12.0.1 default_he082bbe_4
    - clangxx_osx-arm64 12.0.1 h2ae1534_6
    - cmake 3.22.2 h4d639be_0
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - expat 2.4.6 h96cf925_0
    - krb5 1.19.2 h289aae4_3
    - ld64_osx-64 609 hc6b1d1e_7
    - ld64_osx-arm64 609 hf6d2360_7
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcurl 7.81.0 h97da3c1_0
    - libcxx 12.0.1 habf9029_1
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libllvm11 11.1.0 hd011deb_3
    - libllvm12 12.0.1 hd011deb_2
    - libnghttp2 1.47.0 hca56917_0
    - libssh2 1.10.0 hd3787cc_2
    - libuv 1.43.0 h0d85af4_0
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 12.0.1 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - make 4.3 h22f3db7_1
    - nasm 2.15.05 h0d85af4_0
    - ncurses 6.3 he49afe7_0
    - openssl 3.0.0 h0d85af4_2
    - perl 5.32.1 2_h0d85af4_perl5
    - rhash 1.4.1 h35c211d_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
    - zstd 1.5.2 h582d3a0_0
  host:
    - libcxx 12.0.1 h168391b_1
  run:
    - libcxx >=12.0.1
test:
  commands:
    - test -f ${PREFIX}/include/aom/aom.h
    - test -f ${PREFIX}/lib/libaom${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libaom.a
    - test -f ${PREFIX}/lib/pkgconfig/aom.pc
about:
  description: 'AOMedia Video 1 (AV1), is an open, royalty-free video coding format
    designed for

    video transmissions over the Internet.

    '
  dev_url: https://aomedia.googlesource.com/aom/
  home: https://aomedia.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Alliance for Open Media video codec
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - matthiasdiener
