# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jun  3 21:44:56 2022
# ------------------------------------------------

package:
  name: libopencv
  version: 4.5.5
source:
  - fn: opencv-4.5.5.tar.gz
    patches:
      - install_pip_metadata.patch
    sha256: a1cfdcf6619387ca9e232687504da996aaa9f7b5689986b8331ec02cb61d28ad
    url: https://codeload.github.com/opencv/opencv/tar.gz/4.5.5
  - fn: opencv_contrib-4.5.5.tar.gz
    folder: opencv_contrib
    patches:
      - cmake_hdf5_xpile.patch
    sha256: a97c2eaecf7a23c6dbd119a609c6d7fae903e5f9ff5f1fe678933e01c67a6c11
    url: https://codeload.github.com/opencv/opencv_contrib/tar.gz/4.5.5
  - fn: test.avi
    sha256: 78884f64b564a3b06dc6ee731ed33b60c6d8cd864cea07f21d94ba0f90c7b310
    url: https://github.com/opencv/opencv_extra/raw/master/testdata/highgui/video/VID00003-20100701-2204.avi
build:
  ignore_run_exports_from:
    - python
  number: '11'
  run_exports:
    - libopencv >=4.5.5,<4.5.6.0a0
  string: py38he52a0c8_11
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.18.1 h0d85af4_0
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_2
    - clangxx 13.0.1 default_he082bbe_0
    - clangxx_osx-arm64 13.0.1 hdeb254d_2
    - cmake 3.23.2 hf2c7296_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - cross-python_osx-arm64 3.8 23_cpython
    - crossenv 1.2.0 pyhd8ed1ab_7
    - expat 2.4.8 h96cf925_0
    - gettext 0.19.8.1 hd1a6beb_1008
    - krb5 1.19.3 hb98e516_0
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libblas 3.9.0 14_osx64_openblas
    - libcblas 3.9.0 14_osx64_openblas
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcurl 7.83.1 h23f1065_0
    - libcxx 14.0.4 hc203e6f_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libffi 3.4.2 h0d85af4_5
    - libgfortran 5.0.0 9_3_0_h6c81a4c_23
    - libgfortran5 9.3.0 h6c81a4c_23
    - libiconv 1.16 haf1e3a3_0
    - liblapack 3.9.0 14_osx64_openblas
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libnghttp2 1.47.0 hca56917_0
    - libopenblas 0.3.20 openmp_hb3cd9ec_0
    - libprotobuf 3.20.1 h2292cb8_0
    - libssh2 1.10.0 hd3787cc_2
    - libuv 1.43.0 h0d85af4_0
    - libzlib 1.2.12 h6c3fc93_0
    - llvm-openmp 14.0.4 ha654fa7_0
    - llvm-tools 13.0.1 h64f94b2_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.3 h96cf925_1
    - ninja 1.11.0 h1b54a9f_0
    - numpy 1.19.5 py38h5cb586d_3
    - openssl 3.0.3 hfe4f2af_0
    - pkg-config 0.29.2 ha3d46e9_1008
    - popt 1.16 h7b079dc_2002
    - python 3.8.13 h66c20e1_0_cpython
    - python_abi 3.8 2_cp38
    - readline 8.1 h05e3726_0
    - rhash 1.4.1 h0d85af4_0
    - rsync 3.2.3 h7841d2a_4
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.38.5 hd9f0692_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.12 h6c3fc93_0
    - zstd 1.5.2 ha9df2e0_1
  host:
    - aom 3.3.0 h07bb92c_1
    - bzip2 1.0.8 h3422bc3_4
    - c-ares 1.18.1 h3422bc3_0
    - ca-certificates 2022.5.18.1 h4653dfc_0
    - cairo 1.16.0 h3e596be_1011
    - eigen 3.3.9 h260d524_1
    - expat 2.4.8 h6b3803e_0
    - ffmpeg 4.4.1 h4556347_5
    - font-ttf-dejavu-sans-mono 2.37 hab24e00_0
    - font-ttf-inconsolata 3.000 h77eed37_0
    - font-ttf-source-code-pro 2.038 h77eed37_0
    - font-ttf-ubuntu 0.83 hab24e00_0
    - fontconfig 2.14.0 hfb34624_0
    - fonts-conda-ecosystem 1 0
    - fonts-conda-forge 1 0
    - freetype 2.10.4 h17b34a0_1
    - gettext 0.19.8.1 h049c9fb_1008
    - giflib 5.2.1 h27ca646_2
    - glib 2.70.2 hccf11d3_4
    - glib-tools 2.70.2 hccf11d3_4
    - gmp 6.2.1 h9f76cd9_0
    - gnutls 3.7.6 h653af08_2
    - graphite2 1.3.13 h9f76cd9_1001
    - harfbuzz 4.3.0 hd36a07e_0
    - hdf5 1.12.1 nompi_hd9dbc9e_104
    - icu 70.1 h6b3803e_0
    - jasper 2.0.33 hba35424_0
    - jpeg 9e h1c322ee_1
    - krb5 1.19.3 he492e65_0
    - lame 3.100 h27ca646_1001
    - lerc 3.0 hbdafb3b_0
    - libblas 3.9.0 5_h880f123_netlib
    - libcblas 3.9.0 5_h880f123_netlib
    - libcurl 7.83.1 h7965298_0
    - libcxx 14.0.4 h6a5c8ee_0
    - libdeflate 1.10 h3422bc3_0
    - libedit 3.1.20191231 hc8eb9b7_2
    - libev 4.33 h642e427_1
    - libffi 3.4.2 h3422bc3_5
    - libgfortran 5.0.0.dev0 11_0_1_hf114ba7_23
    - libgfortran5 11.0.1.dev0 hf114ba7_23
    - libglib 2.70.2 h67e64d8_4
    - libiconv 1.16 h642e427_0
    - libidn2 2.3.2 h3422bc3_0
    - liblapack 3.9.0 5_h880f123_netlib
    - liblapacke 3.9.0 5_h880f123_netlib
    - libnghttp2 1.47.0 hf30690b_0
    - libpng 1.6.37 hf7e6567_2
    - libprotobuf 3.20.1 h332123e_0
    - libssh2 1.10.0 h7a5bd25_2
    - libtasn1 4.18.0 he4db4b2_1
    - libtiff 4.4.0 h2810ee2_0
    - libunistring 0.9.10 h3422bc3_0
    - libvpx 1.11.0 hc470f4d_3
    - libwebp 1.2.2 h0d20362_0
    - libwebp-base 1.2.2 h3422bc3_1
    - libxml2 2.9.14 h035c1df_0
    - libzlib 1.2.12 h90dfc92_0
    - llvm-openmp 14.0.4 hd125106_0
    - lz4-c 1.9.3 hbdafb3b_1
    - ncurses 6.3 h07bb92c_1
    - nettle 3.7 hc6a1b29_0
    - numpy 1.19.5 py38he594345_3
    - openh264 2.1.1 habe5f53_0
    - openssl 3.0.3 ha287fd2_0
    - pcre 8.45 hbdafb3b_0
    - pixman 0.40.0 h27ca646_0
    - python 3.8.13 hd3575e6_0_cpython
    - python_abi 3.8 2_cp38
    - readline 8.1 hedafd6a_0
    - sqlite 3.38.5 h40dfcc0_0
    - svt-av1 1.1.0 hbe31e94_1
    - tk 8.6.12 he1e0b03_0
    - x264 1!161.3030 h3422bc3_1
    - x265 3.5 hbc6ce65_3
    - xz 5.2.5 h642e427_1
    - zlib 1.2.12 h90dfc92_0
    - zstd 1.5.2 hd705a24_1
  run:
    - ffmpeg >=4.4.1,<5.0a0
    - freetype >=2.10.4,<3.0a0
    - freetype >=2.10.4,<3.0a0
    - harfbuzz >=4.3.0,<5.0a0
    - harfbuzz >=4.3.0,<5.0a0
    - hdf5 >=1.12.1,<1.12.2.0a0
    - jasper >=2.0.33,<3.0a0
    - jpeg >=9e,<10a
    - libcblas >=3.9.0,<4.0a0
    - libcxx >=13.0.1
    - libglib >=2.70.2,<3.0a0
    - liblapack >=3.9.0,<4.0a0
    - liblapacke >=3.9.0,<4.0a0
    - libpng >=1.6.37,<1.7.0a0
    - libprotobuf >=3.20.1,<3.21.0a0
    - libtiff >=4.4.0,<5.0a0
    - libwebp-base >=1.2.2,<2.0a0
    - libzlib >=1.2.12,<1.3.0a0
    - numpy >=1.19.5,<2.0a0
    - python >=3.8,<3.9.0a0 *_cpython
test:
  commands:
    - export MACOSX_DEPLOYMENT_TARGET=11.0
    - export CONDA_BUILD_SYSROOT=/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
    - OPENCV_FLAGS=`pkg-config --cflags opencv4`
    - $CXX -std=c++11 $RECIPE_DIR/test.cpp ${OPENCV_FLAGS} -o test
    - if [[ $(./test) != $PKG_VERSION ]]; then exit 1 ; fi
    - test -f $PREFIX/lib/libopencv_alphamat${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_aruco${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_bgsegm${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_calib3d${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_ccalib${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_core${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_datasets${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_dnn_objdetect${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_dnn_superres${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_dnn${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_dpm${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_face${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_features2d${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_flann${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_fuzzy${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_gapi${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_hfs${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_highgui${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_img_hash${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_imgcodecs${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_imgproc${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_intensity_transform${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_line_descriptor${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_mcc${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_ml${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_objdetect${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_optflow${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_phase_unwrapping${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_photo${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_plot${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_quality${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_rapid${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_reg${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_rgbd${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_saliency${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_shape${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_stereo${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_stitching${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_structured_light${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_superres${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_surface_matching${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_text${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_tracking${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_video${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_videoio${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_videostab${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_wechat_qrcode${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_xfeatures2d${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_ximgproc${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_xobjdetect${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_xphoto${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_bioinspired${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_hdf${SHLIB_EXT}
    - test -f $PREFIX/lib/libopencv_freetype${SHLIB_EXT}
    - mkdir -p cmake_build_test && pushd cmake_build_test
    - cmake -G "Ninja" ..
    - cmake --build . --config Release
    - popd
  files:
    - CMakeLists.txt
    - test.cpp
  requires:
    - clang_osx-arm64 13.*
    - clangxx_osx-arm64 13.*
    - cmake
    - ninja
    - pkg-config
about:
  home: http://opencv.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Computer vision and machine learning software library.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hajapy
    - hmaarrfk
    - jakirkham
    - msarahan
    - ocefpaf
    - patricksnape
    - zym1010
