# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Mar 30 05:35:53 2022
# ------------------------------------------------

package:
  name: expat
  version: 2.4.8
source:
  sha256: a247a7f6bbb21cf2ca81ea4cbb916bfb9717ca523631675f99b3d4a5678dcd16
  url: https://github.com/libexpat/libexpat/releases/download/R_2_4_8/expat-2.4.8.tar.bz2
build:
  number: '0'
  run_exports:
    - expat >=2.4.8,<3.0a0
  string: h6b3803e_0
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_8
    - clangxx 12.0.1 default_he082bbe_4
    - clangxx_osx-arm64 12.0.1 h2ae1534_8
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - ld64_osx-64 609 hc6b1d1e_10
    - ld64_osx-arm64 609 hf6d2360_10
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 13.0.1 hc203e6f_0
    - libllvm12 12.0.1 hd011deb_2
    - libllvm13 13.0.1 h64f94b2_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-tools 12.0.1 hd011deb_2
    - make 4.3 h22f3db7_1
    - openssl 3.0.2 h6c3fc93_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h6c3fc93_1014
  host:
    - libcxx 13.0.1 h6a5c8ee_0
  run:
    - libcxx >=12.0.1
test:
  commands:
    - xmlwf -h
about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
