CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
MACOSX_SDK_VERSION: '10.14'
build_platform: osx-64
c_compiler: clang_bootstrap
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clang_bootstrap
cxx_compiler_version: '13'
dummy_var: '1'
extend_keys:
- ignore_version
- pin_run_as_build
- ignore_build_only_deps
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
macos_machine: arm64-apple-darwin20.0.0
numpy: '1.16'
openturns: '1.18'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  openturns:
    max_pin: x.x
python: '3.9'
r_base: '3.5'
target_platform: osx-arm64
vc: '14'
