# This file created by conda-build 3.21.9
# ------------------------------------------------

package:
  name: libcxx
  version: 14.0.5
source:
  - patches:
      - patches/0002-Support-legacy-standalone-builds.patch
      - patches/0003-Fix-ABI-compatibility-with-system.patch
      - patches/0004-custom-error-message-for-old-sdk.patch
    sha256: c9d27903ba3883c476a83cd515e36e1e07b0585db55692835de11385d9e3c8fa
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.5/llvm-project-14.0.5.src.tar.xz
build:
  ignore_run_exports:
    - libstdcxx-ng
  missing_dso_whitelist:
    - /usr/lib/libc++abi.dylib
  noarch: false
  noarch_python: false
  number: '1'
  string: h04bba0f_1
requirements:
  build:
    - clang_bootstrap_osx-arm64 13.0.1 h80e80bd_2
  run: []
test:
  commands:
    - echo 1
    - test -f $PREFIX/include/c++/v1/iterator
    - bash compile_test.sh
    - if [ -f $PREFIX/lib/libc++abi.dylib ]; then exit 1; fi
  downstreams:
    - libcxx-testing
    - openturns
    - python-symengine
  files:
    - compile_test.sh
    - test_sources
  requires:
    - cctools
    - clang
    - clangxx
    - ld64
    - llvm-tools
about:
  dev_url: https://github.com/llvm/llvm-project
  home: http://libcxx.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: libcxx/LICENSE.TXT
  summary: LLVM C++ standard library
extra:
  copy_test_source_files: true
  feedstock-name: libcxx
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - beckermr
    - h-vetinari
    - inducer
    - isuruf
    - jakirkham
    - timsnyder
