# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Sep 27 14:31:14 2021
# ------------------------------------------------

package:
  name: lerc
  version: '3.0'
source:
  sha256: 8c0148f5c22d823eff7b2c999b0781f8095e49a7d3195f13c68c5541dd5740a1
  url: https://github.com/Esri/lerc/archive/v3.0.tar.gz
build:
  number: '0'
  run_exports:
    - lerc >=3.0,<4.0a0
  string: hbdafb3b_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.17.2 h0d85af4_0
    - ca-certificates 2021.5.30 h033912b_0
    - cctools_osx-64 949.0.1 h6407bdd_22
    - cctools_osx-arm64 949.0.1 h55de48a_22
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_3
    - clangxx 11.1.0 default_he082bbe_1
    - clangxx_osx-arm64 11.1.0 hc50fe25_3
    - cmake 3.21.3 hdbd2f3e_0
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - expat 2.4.1 he49afe7_0
    - krb5 1.19.2 h289aae4_1
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h6a69015_3
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcurl 7.79.1 h97da3c1_1
    - libcxx 12.0.1 habf9029_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_2
    - libnghttp2 1.43.0 hfd382f3_1
    - libssh2 1.10.0 hd3787cc_2
    - libuv 1.42.0 h0d85af4_0
    - llvm-tools 11.1.0 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - make 4.3 h22f3db7_1
    - ncurses 6.2 h2e338ed_4
    - openssl 3.0.0 h0d85af4_0
    - rhash 1.4.1 h35c211d_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.11 h5dbffcc_1
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h7795811_1010
    - zstd 1.5.0 h582d3a0_0
  host:
    - libcxx 12.0.1 h168391b_0
  run:
    - libcxx >=11.1.0
test:
  commands:
    - test -f ${PREFIX}/lib/libLerc${SHLIB_EXT}
    - test -f ${PREFIX}/include/Lerc_types.h
about:
  description: 'LERC is an open-source image or raster format which

    supports rapid encoding and decoding for any pixel type

    (not just RGB or Byte). Users set the maximum compression

    error per pixel while encoding, so the precision of the

    original input image is preserved (within user defined

    error bounds).

    '
  home: https://github.com/Esri/lerc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LERC - Limited Error Raster Compression
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hmaarrfk
