# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Jun  1 05:09:45 2022
# ------------------------------------------------

package:
  name: libtasn1
  version: 4.18.0
source:
  sha256: 4365c154953563d64c67a024b607d1ee75c6db76e0d0f65709ea80a334cd1898
  url: http://ftp.gnu.org/gnu/libtasn1/libtasn1-4.18.0.tar.gz
build:
  number: '1'
  run_exports:
    - libtasn1 >=4.18.0,<5.0a0
  string: he4db4b2_1
requirements:
  build:
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_2
    - clangxx 13.0.1 default_he082bbe_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.4 hc203e6f_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libzlib 1.2.12 h6c3fc93_0
    - llvm-tools 13.0.1 h64f94b2_2
    - make 4.3 h22f3db7_1
    - openssl 3.0.3 hfe4f2af_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host: []
  run: []
test:
  commands:
    - test -f $PREFIX/lib/libtasn1${SHLIB_EXT}
about:
  description: 'The Libtasn1 library provides Abstract Syntax Notation One

    (ASN.1, as specified by the X.680 ITU-T recommendation) parsing and structures
    management,

    and Distinguished Encoding Rules (DER, as per X.690) encoding and decoding functions.

    '
  dev_url: https://gitlab.com/gnutls/libtasn1/
  doc_url: https://www.gnu.org/software/libtasn1/manual/libtasn1.html
  home: https://www.gnu.org/software/libtasn1/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Libtasn1 is the ASN.1 library used by GnuTLS, p11-kit and some other packages
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ceholden
    - gillins
    - ocefpaf
