# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Apr 19 19:59:27 2021
# ------------------------------------------------

package:
  name: bzip2
  version: 1.0.8
source:
  patches:
    - 0001-cross.patch
  sha256: ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269
  url: https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
build:
  number: '4'
  run_exports:
    - bzip2 >=1.0.8,<2.0a0
  string: h3422bc3_4
requirements:
  build:
    - cctools_osx-64 949.0.1 h6407bdd_21
    - cctools_osx-arm64 949.0.1 h55de48a_21
    - clang 11.1.0 h694c41f_0
    - clang-11 11.1.0 default_he082bbe_0
    - clang_osx-arm64 11.1.0 h40be2b1_1
    - clangxx 11.1.0 default_he082bbe_0
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h7660a38_2
    - libclang-cpp11.1 11.1.0 default_he082bbe_0
    - libcxx 11.1.0 habf9029_0
    - libllvm11 11.1.0 hd011deb_2
    - llvm-tools 11.1.0 hd011deb_2
    - make 4.3 h22f3db7_1
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h7795811_1010
  run: []
test:
  commands:
    - bzip2 --help
    - test -f ${PREFIX}/bin/bunzip2
    - test -f ${PREFIX}/bin/bzcat
    - test -f ${PREFIX}/bin/bzcmp
    - test -f ${PREFIX}/bin/bzdiff
    - test -f ${PREFIX}/bin/bzegrep
    - test -f ${PREFIX}/bin/bzfgrep
    - test -f ${PREFIX}/bin/bzgrep
    - test -f ${PREFIX}/bin/bzip2recover
    - test -f ${PREFIX}/bin/bzip2
    - test -f ${PREFIX}/bin/bzless
    - test -f ${PREFIX}/bin/bzmore
    - test -f ${PREFIX}/include/bzlib.h
    - test -f ${PREFIX}/lib/libbz2.a
    - test -f ${PREFIX}/lib/libbz2.dylib
about:
  description: 'Bzip2 is a freely available high-quality data compressor. It typically

    compresses files to within 10% to 15% of the best available techniques,

    whilst being around twice as fast at compression and six times faster

    at decompression.

    '
  doc_url: http://www.bzip.org/docs.html
  home: http://www.bzip.org/
  license: bzip2-1.0.6
  license_family: BSD
  license_file: LICENSE
  summary: high-quality data compressor
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jlanga
    - mingwandroid
    - msarahan
    - pelson
