# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jun 10 00:51:23 2022
# ------------------------------------------------

package:
  name: readline
  version: 8.1.2
source:
  sha256: 7589a2381a8419e68654a47623ce7dfcb756815c8fee726b98f90bf668af7bc6
  url: https://ftp.gnu.org/gnu/readline/readline-8.1.2.tar.gz
build:
  number: '0'
  run_exports:
    - readline >=8.1.2,<9.0a0
  string: h46ed386_0
requirements:
  build:
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_2
    - clangxx 13.0.1 default_he082bbe_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.4 hc203e6f_0
    - libiconv 1.16 haf1e3a3_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.12 h6c3fc93_0
    - llvm-tools 13.0.1 h64f94b2_2
    - make 4.3 h22f3db7_1
    - openssl 3.0.3 hfe4f2af_0
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - ncurses 6.3 h07bb92c_1
  run:
    - ncurses >=6.3,<7.0a0
test:
  commands:
    - test ! -f ${PREFIX}/lib/libreadline.a
    - test -f ${PREFIX}/lib/libreadline${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libhistory.a
    - test -f ${PREFIX}/lib/libhistory${SHLIB_EXT}
about:
  home: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL-3.0-only
  license_file: COPYING
  summary: library for editing command lines as they are typed in
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - asmeurer
    - croth1
    - jakirkham
    - mingwandroid
    - msarahan
    - msarahan
    - ocefpaf
    - pelson
