# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Mar 15 10:10:04 2022
# ------------------------------------------------

package:
  name: krb5
  version: 1.19.3
source:
  patches:
    - 0001-Fix-softpkcs11-build-issues-with-openssl-3.0.patch
  sha256: 131890da54fff2ac339e93facf9d8067f7db53b15181f38104c0b56a6f2acdee
  url: https://github.com/krb5/krb5/archive/krb5-1.19.3-final.tar.gz
build:
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib
  number: '0'
  run_exports:
    - krb5 >=1.19.3,<1.20.0a0
  string: he492e65_0
requirements:
  build:
    - autoconf 2.69 pl5321hc0e15e3_11
    - bison 3.8 he49afe7_0
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h609b070_9
    - cctools_osx-arm64 973.0.1 h7ef2fa9_9
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_7
    - clangxx 12.0.1 default_he082bbe_4
    - clangxx_osx-arm64 12.0.1 h2ae1534_7
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - flex 2.6.4 hcc69e7b_1004
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 609 hc6b1d1e_9
    - ld64_osx-arm64 609 hf6d2360_9
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 13.0.1 hc203e6f_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.16 haf1e3a3_0
    - libllvm12 12.0.1 hd011deb_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 12.0.1 hd011deb_2
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - ncurses 6.3 he49afe7_0
    - openssl 3.0.0 h0d85af4_2
    - perl 5.32.1 2_h0d85af4_perl5
    - pkg-config 0.29.2 h31203cd_1008
    - python 3.10.2 hea1dfa3_4_cpython
    - readline 8.1 h05e3726_0
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.37.0 h23a322b_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2021e he74cb21_0
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
  host:
    - ca-certificates 2021.10.8 h4653dfc_0
    - libcxx 13.0.1 h6a5c8ee_0
    - libedit 3.1.20191231 hc8eb9b7_2
    - ncurses 6.3 hc470f4d_0
    - openssl 3.0.0 h3422bc3_2
  run:
    - libcxx >=12.0.1
    - libedit >=3.1.20191231,<3.2.0a0
    - libedit >=3.1.20191231,<4.0a0
    - openssl >=3.0.0,<4.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libkrb5${SHLIB_EXT}
about:
  home: http://web.mit.edu/kerberos/
  license: MIT
  license_file: doc/notice.rst
  summary: A network authentication protocol.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mariusvniekerk
    - mingwandroid
    - ocefpaf
    - pelson
    - wolfv
