# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Jun 11 17:40:33 2022
# ------------------------------------------------

package:
  name: ffmpeg
  version: 4.4.2
source:
  patches:
    - patches/TARGET_OS_OSX.patch
  sha256: 058efd4b6459bc9df54186f17a989d0af619a793aa62f07e96b88632706d6a17
  url: https://ffmpeg.org/releases/ffmpeg-4.4.2.tar.gz
build:
  number: '0'
  run_exports:
    - ffmpeg >=4.4.2,<5.0a0
  string: h4556347_0
requirements:
  build:
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_2
    - clangxx 13.0.1 default_he082bbe_0
    - clangxx_osx-arm64 13.0.1 hdeb254d_2
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - lame 3.100 h35c211d_1001
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.4 hc203e6f_0
    - libiconv 1.16 haf1e3a3_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.12 h6c3fc93_0
    - llvm-tools 13.0.1 h64f94b2_2
    - make 4.3 h22f3db7_1
    - nasm 2.15.05 h0d85af4_0
    - openssl 3.0.3 hfe4f2af_0
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - aom 3.3.0 h07bb92c_1
    - bzip2 1.0.8 h3422bc3_4
    - freetype 2.10.4 h17b34a0_1
    - gettext 0.19.8.1 h049c9fb_1008
    - gmp 6.2.1 h9f76cd9_0
    - gnutls 3.7.6 h88f254d_4
    - icu 70.1 h6b3803e_0
    - lame 3.100 h27ca646_1001
    - libcxx 14.0.4 h6a5c8ee_0
    - libffi 3.4.2 h3422bc3_5
    - libiconv 1.16 h642e427_0
    - libidn2 2.3.2 h3422bc3_0
    - libpng 1.6.37 hf7e6567_2
    - libtasn1 4.18.0 he4db4b2_1
    - libunistring 0.9.10 h3422bc3_0
    - libvpx 1.11.0 hc470f4d_3
    - libxml2 2.9.14 h035c1df_0
    - libzlib 1.2.12 h90dfc92_0
    - nettle 3.8 h63371fa_0
    - openh264 2.1.1 habe5f53_0
    - p11-kit 0.23.21 h29577a5_4
    - svt-av1 1.1.0 hbe31e94_1
    - x264 1!161.3030 h3422bc3_1
    - x265 3.5 hbc6ce65_3
    - xz 5.2.5 h642e427_1
    - zlib 1.2.12 h90dfc92_0
  run:
    - aom >=3.3.0,<3.4.0a0
    - bzip2 >=1.0.8,<2.0a0
    - freetype >=2.10.4,<3.0a0
    - gmp >=6.2.1,<7.0a0
    - gnutls >=3.7.6,<3.8.0a0
    - lame >=3.100,<3.101.0a0
    - libcxx >=13.0.1
    - libiconv >=1.16,<1.17.0a0
    - libvpx >=1.11.0,<1.12.0a0
    - libxml2 >=2.9.14,<2.10.0a0
    - libzlib >=1.2.12,<1.3.0a0
    - openh264 >=2.1.1,<2.2.0a0
    - svt-av1 >=1.1.0,<1.1.1.0a0
    - x264 >=1!161.3030,<1!162
    - x265 >=3.5,<3.6.0a0
test:
  commands:
    - ffmpeg --help
    - ffmpeg -loglevel panic -protocols | grep "https"
    - ffmpeg -loglevel panic -codecs | grep "libmp3lame"
    - ffmpeg -loglevel panic -codecs | grep "DEVI.S zlib"
    - ffmpeg -loglevel panic -codecs | grep "DEV.LS h264"
    - ffmpeg -loglevel panic -codecs | grep "libx264"
    - ffmpeg -loglevel panic -codecs | grep "libx265"
    - ffmpeg -loglevel panic -codecs | grep "libopenh264"
    - ffmpeg -loglevel panic -codecs | grep "libaom"
    - ffmpeg -loglevel panic -codecs | grep "libsvtav1"
    - test -f $PREFIX/lib/libavdevice${SHLIB_EXT}
    - test -f $PREFIX/lib/libswresample${SHLIB_EXT}
    - test -f $PREFIX/lib/libpostproc${SHLIB_EXT}
    - test -f $PREFIX/lib/libavfilter${SHLIB_EXT}
    - test -f $PREFIX/lib/libavcodec${SHLIB_EXT}
    - test -f $PREFIX/lib/libavformat${SHLIB_EXT}
    - test -f $PREFIX/lib/libswscale${SHLIB_EXT}
    - test -f $PREFIX/lib/libavresample${SHLIB_EXT}
    - test -f $PREFIX/lib/libavutil${SHLIB_EXT}
about:
  dev_url: https://git.ffmpeg.org/ffmpeg.git
  doc_url: https://ffmpeg.org/documentation.html
  home: http://www.ffmpeg.org/
  license: GPL-3.0-or-later
  license_file: COPYING.GPLv3
  summary: Cross-platform solution to record, convert and stream audio and video.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - 183amir
    - benjaminrwilson
    - carlodri
    - danielballan
    - h-vetinari
    - jakirkham
    - matthiasdiener
    - ocefpaf
    - patricksnape
    - sdvillal
