CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
INTERFACE64: '0'
MACOSX_DEPLOYMENT_TARGET: '11.0'
SYMBOLSUFFIX: ''
USE_OPENMP: '1'
build_platform: osx-64
c_compiler: clang
c_compiler_version: '12'
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
extend_keys:
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
- ignore_version
fortran_compiler: gfortran
fortran_compiler_version: '11'
ignore_build_only_deps:
- numpy
- python
llvm_openmp: '12'
lua: '5'
macos_machine: arm64-apple-darwin20.0.0
name_suffix: ''
numpy: '1.16'
perl: 5.32.1
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.9'
r_base: '3.5'
target_platform: osx-arm64
zip_keys:
- - SYMBOLSUFFIX
  - name_suffix
  - INTERFACE64
- - c_compiler_version
  - fortran_compiler_version
