# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: libopenblas
  version: 0.3.20
source:
  sha256: 8495c9affc536253648e942908e88e097f2ec7753ede55aca52e5dead3029e3c
  url: https://github.com/xianyi/OpenBLAS/archive/v0.3.20.tar.gz
build:
  number: 0
  run_exports:
    - libopenblas >=0.3.20,<1.0a0
  string: openmp_h2209c59_0
  track_features: null
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_8
    - clangxx 12.0.1 default_he082bbe_4
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - gfortran_impl_osx-64 9.3.0 h9cc0e5e_23
    - gfortran_impl_osx-arm64 11.0.1.dev0 h3653101_23
    - gfortran_osx-arm64 11.0.1.dev0 h64a2375_15
    - gmp 6.2.1 h2e338ed_0
    - isl 0.22.1 hb1e8313_2
    - ld64_osx-64 609 hc6b1d1e_10
    - ld64_osx-arm64 609 hf6d2360_10
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 13.0.1 hc203e6f_0
    - libgfortran-devel_osx-64 9.3.0 h6c81a4c_23
    - libgfortran-devel_osx-arm64 11.0.1.dev0 hf114ba7_23
    - libgfortran5 9.3.0 h6c81a4c_23
    - libiconv 1.16 haf1e3a3_0
    - libllvm12 12.0.1 hd011deb_2
    - libllvm13 13.0.1 h64f94b2_2
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-openmp 12.0.1 hda6cdc1_1
    - llvm-tools 12.0.1 hd011deb_2
    - mpc 1.2.1 hbb51d92_0
    - mpfr 4.1.0 h0f52abe_1
    - openssl 3.0.2 h6c3fc93_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h6c3fc93_1014
  host:
    - libgfortran 5.0.0.dev0 11_0_1_hf114ba7_23
    - libgfortran5 11.0.1.dev0 hf114ba7_23
    - llvm-openmp 13.0.1 h455960f_1
  run:
    - libgfortran 5.*
    - libgfortran5 >=11.0.1.dev0
    - llvm-openmp >=12.0.1
  run_constrained:
    - openblas >=0.3.20,<0.3.21.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libopenblasp-r0.3.20.dylib
    - nm -g ${PREFIX}/lib/libopenblasp-r0.3.20.dylib | grep dsecnd
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblasp-r0.3.20.dylib']"
about:
  home: http://www.openblas.net/
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - lapack-netlib/LICENSE
  summary: An optimized BLAS library based on GotoBLAS2 1.13 BSD version
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - gillins
    - groutr
    - h-vetinari
    - isuruf
    - jakirkham
