# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Apr 19 20:06:14 2021
# ------------------------------------------------

package:
  name: readline
  version: '8.1'
source:
  sha256: f8ceb4ee131e3232226a17f51b164afc46cd0b9e6cef344be87c65962cb82b02
  url: https://ftp.gnu.org/gnu/readline/readline-8.1.tar.gz
build:
  number: '0'
  run_exports:
    - readline >=8.1,<9.0a0
  string: hedafd6a_0
requirements:
  build:
    - cctools_osx-64 949.0.1 h6407bdd_21
    - cctools_osx-arm64 949.0.1 h55de48a_21
    - clang 11.1.0 h694c41f_0
    - clang-11 11.1.0 default_he082bbe_0
    - clang_osx-arm64 11.1.0 h40be2b1_1
    - clangxx 11.1.0 default_he082bbe_0
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h7660a38_2
    - libclang-cpp11.1 11.1.0 default_he082bbe_0
    - libcxx 11.1.0 habf9029_0
    - libiconv 1.16 haf1e3a3_0
    - libllvm11 11.1.0 hd011deb_2
    - libtool 2.4.6 h2e338ed_1007
    - llvm-tools 11.1.0 hd011deb_2
    - make 4.3 h22f3db7_1
    - pkg-config 0.29.2 h31203cd_1008
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h7795811_1010
  host:
    - ncurses 6.2 h9aa5885_4
  run:
    - ncurses >=6.2,<6.3.0a0
    - ncurses >=6.2,<6.3.0a0
test:
  commands:
    - test ! -f ${PREFIX}/lib/libreadline.a
    - test -f ${PREFIX}/lib/libreadline${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libhistory.a
    - test -f ${PREFIX}/lib/libhistory${SHLIB_EXT}
about:
  home: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL-3.0-only
  license_file: COPYING
  summary: library for editing command lines as they are typed in
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - asmeurer
    - croth1
    - jakirkham
    - mingwandroid
    - msarahan
    - msarahan
    - ocefpaf
    - pelson
