# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Dec 22 18:19:49 2021
# ------------------------------------------------

package:
  name: wheel
  version: 0.37.1
source:
  sha256: e9a504e793efbca1b8e0e9cb979a249cf4a0a7b5b8c9e8b65a5e39d49529c1c4
  url: https://pypi.io/packages/source/w/wheel/wheel-0.37.1.tar.gz
build:
  entry_points:
    - wheel = wheel.cli:main
  noarch: python
  number: '0'
  script: python setup.py install --single-version-externally-managed --record=record.txt
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.10.8 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_11
    - libgomp 11.2.0 h1d223b6_11
    - libnsl 2.0.0 h7f98852_0
    - libstdcxx-ng 11.2.0 he4da1e4_11
    - libzlib 1.2.11 h36c2ea0_1013
    - ncurses 6.2 h58526e2_4
    - openssl 3.0.0 h7f98852_2
    - python 3.8.12 hf930737_2_cpython
    - python_abi 3.8 2_cp38
    - readline 8.1 h46c0cb4_0
    - setuptools 60.0.3 py38h578d9bd_0
    - sqlite 3.37.0 h9cd32fc_0
    - tk 8.6.11 h27826a3_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h36c2ea0_1013
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
test:
  commands:
    - pip check
    - wheel --help
  imports:
    - wheel
    - wheel.cli
  requires:
    - pip
about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
