# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu May 19 13:29:18 2022
# ------------------------------------------------

package:
  name: cryptography
  version: 37.0.2
source:
  sha256: 9fc6a3b4d86e5d41c4d101ff9413a8576bbf85d483464ee73880ce58dd41c9c9
  url: https://github.com/pyca/cryptography/archive/refs/tags/37.0.2.tar.gz
build:
  number: '0'
  script:
    - export PYO3_CROSS_INCLUDE_DIR=$PREFIX/include
    - export PYO3_CROSS_LIB_DIR=$SP_DIR/../
    - export PYO3_CROSS_PYTHON_VERSION=$PY_VER
    - /Users/runner/miniforge3/conda-bld/cryptography_1652967108255/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
      -m pip install . -vv
  string: py39h4cb6239_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.5.18 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - cffi 1.15.0 py39he338e87_0
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_0
    - clangxx 13.0.1 default_he082bbe_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - cross-python_osx-arm64 3.9 23_cpython
    - crossenv 1.2.0 pyhd8ed1ab_7
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 609 hd77a64a_10
    - ld64_osx-arm64 609 hfeae783_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.3 hc203e6f_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.16 haf1e3a3_0
    - libllvm13 13.0.1 h64f94b2_2
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-tools 13.0.1 h64f94b2_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.3 hfe4f2af_0
    - popt 1.16 h7b079dc_2002
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.9.12 h1cc4136_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h7841d2a_4
    - rust 1.60.0 h7e1429e_0
    - rust-std-aarch64-apple-darwin 1.60.0 hf1a8007_0
    - rust-std-x86_64-apple-darwin 1.60.0 h059895a_0
    - rust_osx-arm64 1.60.0 h87d85ca_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.38.5 hd9f0692_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2022a h191b570_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h6c3fc93_1014
    - zstd 1.5.2 ha9df2e0_1
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.5.18 h4653dfc_0
    - cffi 1.15.0 py39h52b1de0_0
    - libffi 3.4.2 h3422bc3_5
    - libzlib 1.2.11 h90dfc92_1014
    - ncurses 6.3 h07bb92c_1
    - openssl 1.1.1o ha287fd2_0
    - pip 22.1 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.9.12 hfc7342c_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 hedafd6a_0
    - semantic_version 2.9.0 pyhd8ed1ab_0
    - setuptools 62.3.1 py39h2804cbe_0
    - setuptools-rust 1.3.0 pyhd8ed1ab_0
    - sqlite 3.38.5 h40dfcc0_0
    - tk 8.6.12 he1e0b03_0
    - typing_extensions 4.2.0 pyha770c72_1
    - tzdata 2022a h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 h90dfc92_1014
  run:
    - cffi >=1.12
    - openssl >=1.1.1o,<1.1.2a
    - python >=3.9,<3.10.0a0
    - python >=3.9,<3.10.0a0 *_cpython
    - python_abi 3.9.* *_cp39
test:
  commands:
    - pytest
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.hazmat.backends
    - cryptography.hazmat.backends.openssl
    - cryptography.hazmat.bindings
    - cryptography.hazmat.bindings.openssl
    - cryptography.hazmat.primitives
    - cryptography.hazmat.primitives.asymmetric
    - cryptography.hazmat.primitives.ciphers
    - cryptography.hazmat.primitives.kdf
    - cryptography.hazmat.primitives.twofactor
    - cryptography.x509
  requires:
    - cryptography-vectors 37.0.2.*
    - hypothesis
    - iso8601
    - pretend
    - pytest
    - pytest-benchmark
    - pytest-subtests
    - pytz
  source_files:
    - tests
about:
  description: 'cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces

    to common cryptographic algorithms such as symmetric ciphers, message

    digests, and key derivation functions..

    '
  dev_url: https://github.com/pyca/cryptography
  doc_source_url: https://github.com/pyca/cryptography/blob/master/docs/index.rst
  doc_url: http://cryptography.readthedocs.io/
  home: cryptography.io
  license: Apache-2.0 AND BSD-3-Clause AND PSF-2.0 AND MIT
  license_family: BSD
  license_file: LICENSE
  summary: cryptography is a package designed to expose cryptographic primitives and
    recipes to Python developers.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - ocefpaf
