# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jul 30 18:14:47 2021
# ------------------------------------------------

package:
  name: lz4-c
  version: 1.9.3
source:
  fn: lz4-1.9.3.tar.gz
  patches:
    - patches/CVE-2021-3520.patch
  sha256: 030644df4611007ff7dc962d981f390361e6c97a34e5cbc393ddfbe019ffe2c1
  url: https://github.com/lz4/lz4/archive/v1.9.3.tar.gz
build:
  number: '1'
  run_exports:
    - lz4-c >=1.9.3,<1.10.0a0
  string: hbdafb3b_1
requirements:
  build:
    - cctools_osx-64 949.0.1 h6407bdd_22
    - cctools_osx-arm64 949.0.1 h55de48a_22
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_2
    - clangxx 11.1.0 default_he082bbe_1
    - clangxx_osx-arm64 11.1.0 hc50fe25_2
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h7660a38_2
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_0
    - llvm-tools 11.1.0 hd011deb_2
    - make 4.3 h22f3db7_1
    - patch 2.7.6 hbcf498f_1002
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h7795811_1010
  host:
    - libcxx 12.0.1 h168391b_0
  run:
    - libcxx >=11.1.0
about:
  description: 'LZ4 is lossless compression algorithm, providing compression speed
    at 400

    MB/s per core (0.16 Bytes/cycle). It features an extremely fast decoder,

    with speed in multiple GB/s per core (0.71 Bytes/cycle). A high compression

    derivative, called LZ4_HC, is available, trading customizable CPU time for

    compression ratio. LZ4 library is provided as open source software using a

    BSD license.

    '
  home: https://www.lz4.org
  license: BSD-2-Clause
  license_file: lib/LICENSE
  summary: Extremely Fast Compression algorithm
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mingwandroid
    - rmax
    - wesm
    - xhochy
