# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: libnghttp2
  version: 1.47.0
source:
  sha256: 62f50f0e9fc479e48b34e1526df8dd2e94136de4c426b7680048181606832b7c
  url: https://github.com/nghttp2/nghttp2/releases/download/v1.47.0/nghttp2-1.47.0.tar.gz
build:
  number: 0
  run_exports:
    - libnghttp2 >=1.47.0,<2.0a0
  string: hf30690b_0
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h609b070_7
    - cctools_osx-arm64 973.0.1 hd1d4517_7
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_6
    - clangxx 12.0.1 default_he082bbe_4
    - clangxx_osx-arm64 12.0.1 h2ae1534_6
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - ld64_osx-64 609 hc6b1d1e_7
    - ld64_osx-arm64 609 hf6d2360_7
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 12.0.1 habf9029_1
    - libllvm11 11.1.0 hd011deb_3
    - libllvm12 12.0.1 hd011deb_2
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 12.0.1 hd011deb_2
    - make 4.3 h22f3db7_1
    - openssl 3.0.0 h0d85af4_2
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h9173be1_1013
  host:
    - c-ares 1.18.1 h3422bc3_0
    - ca-certificates 2021.10.8 h4653dfc_0
    - libcxx 12.0.1 h168391b_1
    - libev 4.33 h642e427_1
    - libzlib 1.2.11 hee7b306_1013
    - openssl 3.0.0 h3422bc3_2
    - zlib 1.2.11 hee7b306_1013
  run:
    - c-ares >=1.18.1,<2.0a0
    - c-ares >=1.7.5
    - libcxx >=12.0.1
    - libev >=4.11
    - libev >=4.33,<4.34.0a0
    - libzlib >=1.2.11,<1.3.0a0
    - openssl >=3.0.0,<4.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - nghttp -nv https://nghttp2.org
    - test ! -f ${PREFIX}/lib/libnghttp2.a
about:
  description: 'This is an implementation of the Hypertext Transfer Protocol version
    2 in C.


    The framing layer of HTTP/2 is implemented as a reusable C library. On top

    of that, we have implemented an HTTP/2 client, server and proxy. We have

    also developed load test and benchmarking tools for HTTP/2.

    '
  dev_url: https://github.com/nghttp2/nghttp2
  doc_url: https://nghttp2.org/documentation/
  home: http://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - cpaulik
    - mariusvniekerk
    - wolfv
