CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
build_platform: osx-64
c_compiler: clang
c_compiler_version: '12'
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
extend_keys:
- pin_run_as_build
- ignore_build_only_deps
- extend_keys
- ignore_version
fontconfig: '2.13'
fortran_compiler: gfortran
freetype: '2'
glib: '2'
icu: '70'
ignore_build_only_deps:
- python
- numpy
libpng: '1.6'
lua: '5'
macos_machine: arm64-apple-darwin20.0.0
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  libpng:
    max_pin: x.x
  xz:
    max_pin: x.x
  zlib:
    max_pin: x.x
pixman: '0'
python: '3.9'
r_base: '3.5'
target_platform: osx-arm64
xz: '5.2'
zlib: '1.2'
