# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Jun 13 11:42:53 2022
# ------------------------------------------------

package:
  name: libtiff
  version: 4.4.0
source:
  patches:
    - patches/use_unix_io.patch
  sha256: 917223b37538959aca3b790d2d73aa6e626b688e02dcda272aec24c2f498abed
  url: https://download.osgeo.org/libtiff/tiff-4.4.0.tar.gz
build:
  missing_dso_whitelist:
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib
  number: '1'
  run_exports:
    - libtiff >=4.4.0,<5.0a0
  string: hcbbed22_1
requirements:
  build:
    - autoconf 2.69 pl5321hc0e15e3_11
    - automake 1.16.5 pl5321h694c41f_0
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_2
    - clangxx 13.0.1 default_he082bbe_0
    - clangxx_osx-arm64 13.0.1 hdeb254d_2
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.5 hce7ea42_1
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.5 h41df66c_0
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.12 h6c3fc93_0
    - llvm-tools 13.0.1 h64f94b2_2
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - openssl 3.0.3 hfe4f2af_0
    - perl 5.32.1 2_h0d85af4_perl5
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - jpeg 9e h1c322ee_1
    - lerc 3.0 hbdafb3b_0
    - libcxx 14.0.5 h04bba0f_1
    - libdeflate 1.12 he4db4b2_0
    - libwebp-base 1.2.2 h3422bc3_1
    - libzlib 1.2.12 h90dfc92_0
    - lz4-c 1.9.3 hbdafb3b_1
    - xz 5.2.5 h642e427_1
    - zlib 1.2.12 h90dfc92_0
    - zstd 1.5.2 hd705a24_1
  run:
    - jpeg >=9e,<10a
    - lerc >=3.0,<4.0a0
    - libcxx >=13.0.1
    - libdeflate >=1.12,<1.13.0a0
    - libwebp-base
    - libzlib >=1.2.12,<1.3.0a0
    - xz >=5.2.5,<5.3.0a0
    - zstd >=1.5.2,<1.6.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libtiff.a
    - test -f ${PREFIX}/lib/libtiffxx.a
    - test -f ${PREFIX}/lib/libtiff.dylib
    - test -f ${PREFIX}/lib/libtiffxx.dylib
  downstreams:
    - pillow >=8
    - py-opencv >=4
    - tifffile
about:
  description: 'This software provides support for the Tag Image File Format (TIFF),
    a

    widely used format for storing image data.

    '
  doc_url: http://www.libtiff.org/document.html
  home: http://www.libtiff.org/
  license: HPND
  license_file: COPYRIGHT
  summary: Support for the Tag Image File Format (TIFF).
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hmaarrfk
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
