# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed May 25 07:40:16 2022
# ------------------------------------------------

package:
  name: ruamel_yaml
  version: 0.15.80
source:
  sha256: 4f203351575dba0829c7b1e5d376d08cf5f58e4a2b844e8ce552b3e41cd414e6
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.15.80.tar.gz
build:
  number: '1007'
  string: py39h9eb174b_1007
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_1
    - clangxx 13.0.1 default_he082bbe_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - cross-python_osx-arm64 3.9 23_cpython
    - crossenv 1.2.0 pyhd8ed1ab_7
    - cython 0.29.30 py39hd408605_0
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.3 hc203e6f_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.16 haf1e3a3_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.3 h41df66c_0
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-tools 13.0.1 h64f94b2_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.3 hfe4f2af_0
    - popt 1.16 h7b079dc_2002
    - python 3.9.12 h1cc4136_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h7841d2a_4
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.38.5 hd9f0692_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2022a h191b570_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h6c3fc93_1014
    - zstd 1.5.2 ha9df2e0_1
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.5.18.1 h4653dfc_0
    - cython 0.29.30 py39h6e3512e_0
    - libcxx 14.0.3 h6a5c8ee_0
    - libffi 3.4.2 h3422bc3_5
    - libzlib 1.2.11 h90dfc92_1014
    - ncurses 6.3 h07bb92c_1
    - openssl 3.0.3 ha287fd2_0
    - pip 22.1.1 pyhd8ed1ab_0
    - python 3.9.12 h14b404e_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 hedafd6a_0
    - setuptools 62.3.2 py39h2804cbe_0
    - sqlite 3.38.5 h40dfcc0_0
    - tk 8.6.12 he1e0b03_0
    - tzdata 2022a h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h642e427_1
    - yaml 0.2.5 h3422bc3_2
    - zlib 1.2.11 h90dfc92_1014
  run:
    - python >=3.9,<3.10.0a0
    - python >=3.9,<3.10.0a0 *_cpython
    - python_abi 3.9.* *_cp39
    - yaml >=0.2.5,<0.3.0a0
test:
  commands:
    - if pip show ruamel.yaml; then exit 1; fi
    - $PYTHON -m pip install ruamel.yaml
    - $PYTHON -c "import ruamel.yaml"
    - pip check
  imports:
    - ruamel_yaml
    - ruamel_yaml.ext._ruamel_yaml
  requires:
    - pip
about:
  home: https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A patched copy of ruamel.yaml.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mbargull
