# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu May 19 23:09:04 2022
# ------------------------------------------------

package:
  name: svt-av1
  version: 1.1.0
source:
  sha256: 1c211b944ac83ef013fe91aee96c01289da4e3762c1e2f265449f3a964f8e4bc
  url: https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.1.0/SVT-AV1-v1.1.0.tar.gz
build:
  number: '1'
  run_exports:
    - svt-av1 >=1.1.0,<1.1.1.0a0
  string: hbe31e94_1
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.18.1 h0d85af4_0
    - ca-certificates 2022.5.18 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_0
    - clangxx 13.0.1 default_he082bbe_0
    - clangxx_osx-arm64 13.0.1 hdeb254d_0
    - cmake 3.23.1 h35a7dd9_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - expat 2.4.8 h96cf925_0
    - krb5 1.19.3 hb98e516_0
    - ld64_osx-64 609 hd77a64a_10
    - ld64_osx-arm64 609 hfeae783_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcurl 7.83.1 h23f1065_0
    - libcxx 14.0.3 hc203e6f_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libllvm13 13.0.1 h64f94b2_2
    - libnghttp2 1.47.0 hca56917_0
    - libssh2 1.10.0 hd3787cc_2
    - libuv 1.43.0 h0d85af4_0
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-tools 13.0.1 h64f94b2_2
    - lz4-c 1.9.3 he49afe7_1
    - make 4.3 h22f3db7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.3 hfe4f2af_0
    - rhash 1.4.1 h0d85af4_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.5 haf1e3a3_1
    - yasm 1.3.0 h0d85af4_1003
    - zlib 1.2.11 h6c3fc93_1014
    - zstd 1.5.2 ha9df2e0_1
  host:
    - libcxx 14.0.3 h6a5c8ee_0
  run:
    - libcxx >=13.0.1
test:
  commands:
    - test -f $PREFIX/include/svt-av1/EbSvtAv1.h
    - test -f $PREFIX/lib/libSvtAv1Dec${SHLIB_EXT}
    - test -f $PREFIX/lib/libSvtAv1Enc${SHLIB_EXT}
about:
  description: 'The Scalable Video Technology for AV1 (SVT-AV1 Encoder and Decoder)
    is an

    AV1-compliant encoder/decoder library core.

    '
  home: https://gitlab.com/AOMediaCodec/SVT-AV1
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The Scalable Video Technology for AV1 encoder/decoder library.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - matthiasdiener
