# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: python
  version: 3.8.13
source:
  - md5: c4b7100dcaace9d33ab1fda9a3a038d6
    patches:
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0003-Support-cross-compiling-byte-code.patch
      - patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
      - patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0006-Win32-Do-not-download-externals.patch
      - patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
      - patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0010-Unvendor-openssl.patch
      - patches/0011-Unvendor-sqlite3.patch
      - patches/0012-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0014-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
      - patches/0015-Doing-d1trimfile.patch
      - patches/0016-cross-compile-darwin.patch
      - patches/0018-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0019-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
      - patches/0020-Unvendor-bzip2.patch
      - patches/0021-Unvendor-libffi.patch
      - patches/0022-Unvendor-tcltk.patch
      - patches/0023-unvendor-xz.patch
      - patches/0024-unvendor-zlib.patch
      - patches/0025-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
    url: https://www.python.org/ftp/python/3.8.13/Python-3.8.13.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - clangxx_osx-arm64 12.*
  no_link: null
  number: 0
  run_exports:
    noarch:
      - python
    weak:
      - python_abi 3.8.* *_cp38
  script_env:
    - CONDA_FORGE=yes
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  skip_compile_pyc:
    - '*.py'
  string: hd3575e6_0_cpython
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_8
    - clangxx 12.0.1 default_he082bbe_4
    - clangxx_osx-arm64 12.0.1 h2ae1534_8
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - ld64_osx-64 609 hc6b1d1e_10
    - ld64_osx-arm64 609 hf6d2360_10
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 13.0.1 hc203e6f_0
    - libiconv 1.16 haf1e3a3_0
    - libllvm12 12.0.1 hd011deb_2
    - libllvm13 13.0.1 h64f94b2_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 12.0.1 hd011deb_2
    - make 4.3 h22f3db7_1
    - openssl 3.0.2 h6c3fc93_1
    - pkg-config 0.29.2 h31203cd_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h9173be1_1013
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2021.10.8 h4653dfc_0
    - libffi 3.4.2 h3422bc3_5
    - libzlib 1.2.11 hee7b306_1013
    - ncurses 6.3 hc470f4d_0
    - openssl 3.0.2 h90dfc92_1
    - readline 8.1 hedafd6a_0
    - sqlite 3.37.1 h7e3ccbd_0
    - tk 8.6.12 he1e0b03_0
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 hee7b306_1013
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libffi >=3.4.2,<3.5.0a0
    - libzlib >=1.2.11,<1.3.0a0
    - ncurses >=6.3,<7.0a0
    - openssl >=3.0.2,<4.0a0
    - readline >=8.1,<9.0a0
    - sqlite >=3.37.1,<4.0a0
    - tk >=8.6.12,<8.7.0a0
    - xz >=5.2.5,<5.3.0a0
  run_constrained:
    - python_abi 3.8.* *_cp38
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -m venv test-venv
    - test-venv/bin/python -c "import ctypes"
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.8.13
    - popd
    - popd
    - python run_test.py
    - test ! -f default.profraw
    - python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
  downstreams:
    - cython
    - setuptools
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils/*
    - tests/prefix-replacement/*
  requires:
    - clang_osx-arm64 12.*
    - clangxx_osx-arm64 12.*
    - cmake
    - ninja
    - ripgrep
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - katietz
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
    - xhochy
