# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri May 20 23:44:00 2022
# ------------------------------------------------

package:
  name: harfbuzz
  version: 4.3.0
source:
  patches: null
  sha256: 32184860ddc0b264ff95010e1c64e596bd746fe4c2e34014a1185340cdddeba6
  url: https://github.com/harfbuzz/harfbuzz/archive/4.3.0.tar.gz
build:
  number: '0'
  run_exports:
    - harfbuzz >=4.3.0,<5.0a0
  string: hd36a07e_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.5.18.1 h033912b_0
    - cairo 1.16.0 h1680b09_1011
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_0
    - clangxx 13.0.1 default_he082bbe_0
    - clangxx_osx-arm64 13.0.1 hdeb254d_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - expat 2.4.8 h96cf925_0
    - font-ttf-dejavu-sans-mono 2.37 hab24e00_0
    - font-ttf-inconsolata 3.000 h77eed37_0
    - font-ttf-source-code-pro 2.038 h77eed37_0
    - font-ttf-ubuntu 0.83 hab24e00_0
    - fontconfig 2.14.0 h676cef8_0
    - fonts-conda-ecosystem 1 0
    - fonts-conda-forge 1 0
    - freetype 2.10.4 h4cff582_1
    - g-ir-build-tools 1.72.0 py310h190a8f5_1
    - g-ir-host-tools 1.72.0 h5734cbb_1
    - gettext 0.19.8.1 hd1a6beb_1008
    - glib 2.70.2 hcf210ce_4
    - glib-tools 2.70.2 hcf210ce_4
    - gobject-introspection 1.72.0 py310hb7eb778_1
    - graphite2 1.3.13 h2e338ed_1001
    - icu 70.1 h96cf925_0
    - ld64_osx-64 609 hd77a64a_10
    - ld64_osx-arm64 609 hfeae783_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.3 hc203e6f_0
    - libffi 3.4.2 h0d85af4_5
    - libgirepository 1.72.0 h0bde3a9_1
    - libglib 2.70.2 hf1fb8c0_4
    - libiconv 1.16 haf1e3a3_0
    - libllvm13 13.0.1 h64f94b2_2
    - libpng 1.6.37 h7cec526_2
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-tools 13.0.1 h64f94b2_2
    - meson 0.62.1 pyhd8ed1ab_0
    - ncurses 6.3 h96cf925_1
    - ninja 1.11.0 h1b54a9f_0
    - openssl 3.0.3 hfe4f2af_0
    - pcre 8.45 he49afe7_0
    - pixman 0.40.0 hbcb3906_0
    - pkg-config 0.29.2 ha3d46e9_1008
    - pthread-stubs 0.4 hc929b4f_1001
    - python 3.10.4 h1cc4136_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h05e3726_0
    - setuptools 62.3.2 py310h2ec42d9_0
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.38.5 hd9f0692_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2022a h191b570_0
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h6c3fc93_1014
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.5.18.1 h4653dfc_0
    - cairo 1.16.0 h3e596be_1011
    - expat 2.4.8 h6b3803e_0
    - font-ttf-dejavu-sans-mono 2.37 hab24e00_0
    - font-ttf-inconsolata 3.000 h77eed37_0
    - font-ttf-source-code-pro 2.038 h77eed37_0
    - font-ttf-ubuntu 0.83 hab24e00_0
    - fontconfig 2.14.0 hfb34624_0
    - fonts-conda-ecosystem 1 0
    - fonts-conda-forge 1 0
    - freetype 2.10.4 h17b34a0_1
    - gettext 0.19.8.1 h049c9fb_1008
    - glib 2.70.2 hccf11d3_4
    - glib-tools 2.70.2 hccf11d3_4
    - graphite2 1.3.13 h9f76cd9_1001
    - icu 70.1 h6b3803e_0
    - libcxx 14.0.3 h6a5c8ee_0
    - libffi 3.4.2 h3422bc3_5
    - libglib 2.70.2 h67e64d8_4
    - libiconv 1.16 h642e427_0
    - libpng 1.6.37 hf7e6567_2
    - libzlib 1.2.11 h90dfc92_1014
    - ncurses 6.3 h07bb92c_1
    - openssl 3.0.3 ha287fd2_0
    - pcre 8.45 hbdafb3b_0
    - pixman 0.40.0 h27ca646_0
    - python 3.10.4 h14b404e_0_cpython
    - readline 8.1 hedafd6a_0
    - sqlite 3.38.5 h40dfcc0_0
    - tk 8.6.12 he1e0b03_0
    - tzdata 2022a h191b570_0
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 h90dfc92_1014
  run:
    - cairo >=1.16.0,<1.17.0a0
    - cairo >=1.16.0,<1.17.0a0
    - freetype >=2.10.4,<3.0a0
    - freetype >=2.10.4,<3.0a0
    - graphite2
    - icu >=70.1,<71.0a0
    - libcxx >=13.0.1
    - libglib >=2.70.2,<3.0a0
test:
  commands:
    - test -f $PREFIX/lib/libharfbuzz-gobject${SHLIB_EXT}
    - test -f $PREFIX/lib/libharfbuzz-icu${SHLIB_EXT}
    - test -f $PREFIX/lib/libharfbuzz${SHLIB_EXT}
    - test -f $PREFIX/include/harfbuzz/hb-ft.h
    - test -f $PREFIX/lib/girepository-1.0/HarfBuzz-0.0.typelib
  requires:
    - pygobject
about:
  description: 'HarfBuzz is a text shaping library. New Harbuzz targets various font

    technologies while Old HarfBuzz targets only OpenType fonts.

    '
  dev_url: https://github.com/behdad/harfbuzz
  doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
  license: MIT
  license_file: COPYING
  summary: An OpenType text shaping engine.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - pkgw
    - tschoonj
