# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon May  2 15:58:25 2022
# ------------------------------------------------

package:
  name: libxml2
  version: 2.9.14
source:
  patches:
    - 0002-Make-and-install-a-pkg-config-file-on-Windows.patch
    - 0004-CVE-2017-8872.patch
  sha256: 80efe9e6b48f8aa7b9b0c47be427e2ef2dbfb2999124220ffbc0f43ca6adb98c
  url: https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.9.14/libxml2-v2.9.14.tar.gz
build:
  number: '0'
  run_exports:
    - libxml2 >=2.9.14,<2.10.0a0
  string: h035c1df_0
requirements:
  build:
    - autoconf 2.69 pl5321hc0e15e3_11
    - automake 1.16.5 pl5321h694c41f_0
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_0
    - clangxx 13.0.1 default_he082bbe_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - ld64_osx-64 609 hd77a64a_10
    - ld64_osx-arm64 609 hfeae783_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 13.0.1 hc203e6f_0
    - libiconv 1.16 haf1e3a3_0
    - libllvm13 13.0.1 h64f94b2_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-tools 13.0.1 h64f94b2_2
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - openssl 3.0.2 h6c3fc93_1
    - perl 5.32.1 2_h0d85af4_perl5
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - icu 70.1 h6b3803e_0
    - libcxx 13.0.1 h6a5c8ee_0
    - libiconv 1.16 h642e427_0
    - libzlib 1.2.11 h90dfc92_1014
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 h90dfc92_1014
  run:
    - icu >=70.1,<71.0a0
    - libiconv >=1.16,<1.17.0a0
    - libiconv >=1.16,<1.17.0a0
    - libzlib >=1.2.11,<1.3.0a0
    - xz >=5.2.5,<5.3.0a0
    - xz >=5.2.5,<5.3.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - xmllint test.xml
  files:
    - test.xml
about:
  description: 'Though libxml2 is written in C a variety of language

    bindings make it available in other environments.

    '
  dev_url: https://git.gnome.org/browse/libxml2/
  doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/index.html
  doc_url: http://xmlsoft.org/html/index.html
  home: http://xmlsoft.org/
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: The XML C parser and toolkit of Gnome
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - gillins
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
    - scopatz
