# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jun 10 13:41:04 2022
# ------------------------------------------------

package:
  name: p11-kit
  version: 0.24.1
source:
  sha256: d8be783efd5cd4ae534cee4132338e3f40f182c3205d23b200094ec85faaaef8
  url: https://github.com/p11-glue/p11-kit/releases/download/0.24.1/p11-kit-0.24.1.tar.xz
build:
  number: '0'
  run_exports:
    - p11-kit >=0.24.1,<0.25.0a0
  string: h29577a5_0
requirements:
  build:
    - autoconf 2.69 pl5321hc0e15e3_11
    - automake 1.16.5 pl5321h694c41f_0
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_2
    - clangxx 13.0.1 default_he082bbe_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.4 hc203e6f_0
    - libiconv 1.16 haf1e3a3_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.12 h6c3fc93_0
    - llvm-tools 13.0.1 h64f94b2_2
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - openssl 3.0.3 hfe4f2af_0
    - perl 5.32.1 2_h0d85af4_perl5
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - ca-certificates 2022.5.18.1 h4653dfc_0
    - libffi 3.4.2 h3422bc3_5
    - libtasn1 4.18.0 he4db4b2_1
  run:
    - libffi >=3.4.2,<3.5.0a0
    - libffi >=3.4.2,<3.5.0a0
    - libtasn1 >=4.18.0,<5.0a0
test:
  commands:
    - p11-kit -h
about:
  home: https://github.com/p11-glue/p11-kit
  license: MIT
  license_file: COPYING
  summary: Provides a way to load and enumerate PKCS#11 modules
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chapmanb
    - leofang
    - marcelotrevisani
