# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libssh2
  version: 1.10.0
source:
  patches:
    - 246c7cb0184b9e1a882c753b412825799c7a9118.patch
  sha256: 2d64e90f3ded394b91d3a2e774ca203a4179f69aebee03003e5a6fa621e41d51
  url: https://www.libssh2.org/download/libssh2-1.10.0.tar.gz
build:
  number: 2
  run_exports:
    - libssh2 >=1.10.0,<2.0a0
  string: h7a5bd25_2
requirements:
  build:
    - cctools_osx-arm64 973.0.1 h11dea68_2
    - clang_bootstrap_osx-arm64 11.1.0 h75a6d7f_3
    - cmake-no-system 3.16.5 he49afe7_0
    - ld64_osx-arm64 609 hd44e4ec_2
    - ldid 2.1.2 h6a69015_3
    - libcxx 12.0.1 habf9029_0
    - libllvm12 12.0.1 hd011deb_2
    - make 4.3 h22f3db7_1
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h7795811_1010
  host:
    - ca-certificates 2021.5.30 h4653dfc_0
    - openssl 3.0.0 h3422bc3_0
    - zlib 1.2.11 h31e879b_1009
  run:
    - openssl >=3.0.0,<4.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/include/libssh2.h
    - test -f $PREFIX/include/libssh2_publickey.h
    - test -f $PREFIX/include/libssh2_sftp.h
    - test ! -f $PREFIX/lib/libssh2.a
    - test -f $PREFIX/lib/libssh2${SHLIB_EXT}
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  feedstock-name: libssh2
  final: true
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
    - shadowwalkersb
    - xhochy
