# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: libglib
  version: 2.70.2
source:
  patches:
    - hardcoded-paths.patch
    - skip-gio-tests-meson.build.patch
    - skip-gio-tests-resources.c.patch
    - skip-glib-tests-fileutils.c.patch
    - skip-glib-tests-gdatetime.c.patch
  sha256: 0551459c85cd3da3d58ddc9016fd28be5af503f5e1615a71ba5b512ac945806f
  url: https://download.gnome.org/sources/glib/2.70/glib-2.70.2.tar.xz
build:
  ignore_run_exports_from:
    - python *
  number: 4
  run_exports:
    - libglib >=2.70.2,<3.0a0
  string: h67e64d8_4
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h609b070_7
    - cctools_osx-arm64 973.0.1 hd1d4517_7
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h7730a26_6
    - clangxx 11.1.0 default_he082bbe_1
    - clangxx_osx-arm64 11.1.0 h862bf99_6
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - ld64_osx-64 609 h6adca69_7
    - ld64_osx-arm64 609 h70d1651_7
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_1
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.16 haf1e3a3_0
    - libllvm11 11.1.0 hd011deb_3
    - libllvm12 12.0.1 hd011deb_2
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 11.1.0 hd011deb_3
    - meson 0.61.1 pyhd8ed1ab_0
    - ncurses 6.3 he49afe7_0
    - ninja 1.10.2 h940c156_1
    - openssl 3.0.0 h0d85af4_2
    - pkg-config 0.29.2 h31203cd_1008
    - python 3.10.2 hea1dfa3_3_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h05e3726_0
    - setuptools 60.8.2 py310h2ec42d9_0
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.37.0 h23a322b_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.11 h5dbffcc_1
    - tzdata 2021e he74cb21_0
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
  host:
    - gettext 0.19.8.1 h049c9fb_1008
    - libcxx 12.0.1 h168391b_1
    - libffi 3.4.2 h3422bc3_5
    - libiconv 1.16 h642e427_0
    - libzlib 1.2.11 hee7b306_1013
    - pcre 8.45 hbdafb3b_0
    - zlib 1.2.11 hee7b306_1013
  run:
    - gettext >=0.19.8.1,<1.0a0
    - libcxx >=11.1.0
    - libffi >=3.4.2,<3.5.0a0
    - libiconv >=1.16,<1.17.0a0
    - libzlib >=1.2.11,<1.3.0a0
    - pcre >=8.45,<9.0a0
  run_constrained:
    - glib 2.70.2 *_4
test:
  commands:
    - test -f ${PREFIX}/lib/libglib-2.0.0.dylib
    - test ! -f ${PREFIX}/lib/libgobject-2.0.la
    - test ! -f ${PREFIX}/lib/libglib-2.0${SHLIB_EXT}
    - test -f ${PREFIX}/lib/pkgconfig/glib-2.0.pc
    - test -f ${PREFIX}/etc/conda/activate.d/libglib_activate.sh
    - test -f ${PREFIX}/etc/conda/deactivate.d/libglib_deactivate.sh
about:
  home: https://developer.gnome.org/glib/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: Provides core application building blocks for libraries and applications
    written in C.
extra:
  copy_test_source_files: true
  feedstock-name: glib
  final: true
  recipe-maintainers:
    - ccordoba12
    - isuruf
    - jakirkham
    - ocefpaf
    - pkgw
    - scopatz
    - tschoonj
    - xhochy
