# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Jan  2 10:21:19 2021
# ------------------------------------------------

package:
    name: openh264
    version: 2.1.1
source:
    fn: openh264-v2.1.1.tar.gz
    sha256: af173e90fce65f80722fa894e1af0d6b07572292e76de7b65273df4c0a8be678
    url: https://github.com/cisco/openh264/archive/v2.1.1.tar.gz
build:
    number: '0'
    run_exports:
        - openh264 >=2.1.1,<2.2.0a0
    string: habe5f53_0
requirements:
    build:
        - cctools_osx-arm64 949.0.1 h9541561_19
        - clang 11.0.0 h694c41f_2
        - clang-11 11.0.0 default_h9e6edd0_2
        - clang_osx-arm64 11.0.0 h40be2b1_8
        - clangxx 11.0.0 default_h9e6edd0_2
        - clangxx_osx-arm64 11.0.0 hc50fe25_8
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - ld64_osx-64 530 hea264c1_19
        - ld64_osx-arm64 530 ha0a8365_19
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h9e6edd0_2
        - libcxx 11.0.0 h4c3b8ed_1
        - libiconv 1.16 haf1e3a3_0
        - libllvm11 11.0.0 hf85e3d2_0
        - llvm-tools 11.0.0 hf85e3d2_0
        - make 4.3 h22f3db7_1
        - nasm 2.13.02 h1de35cc_1001
        - pkg-config 0.29.2 h31203cd_1008
        - tapi 1100.0.11 h9ce4665_0
        - zlib 1.2.11 h7795811_1010
    host:
        - libcxx 11.0.0 h7cf67bf_1
        - zlib 1.2.11 h31e879b_1009
    run:
        - libcxx >=11.0.0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - h264enc -h
        - test -f $PREFIX/bin/h264dec
        - test -f $PREFIX/lib/libopenh264.dylib
about:
    dev_url: https://github.com/cisco/openh264
    doc_url: https://github.com/cisco/openh264
    home: http://www.openh264.org/
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: OpenH264 is a codec library which supports H.264 encoding and decoding
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - 183amir
        - sdvillal
