# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Nov  2 18:35:27 2020
# ------------------------------------------------

package:
    name: pixman
    version: 0.40.0
source:
    patches: null
    sha256: 6d200dec3740d9ec4ec8d1180e25779c00bc749f94278c8b9021f5534db223fc
    url: http://cairographics.org/releases/pixman-0.40.0.tar.gz
build:
    number: '0'
    run_exports:
        - pixman >=0.40.0,<1.0a0
    string: h27ca646_0
requirements:
    build:
        - cctools_osx-arm64 949.0.1 h1c9b417_16
        - clang 11.0.0 1
        - clang-11 11.0.0 default_h000dee7_1
        - clang_osx-arm64 11.0.0 h40be2b1_3
        - clangxx 11.0.0 default_hf57f61e_1
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - ld64_osx-64 530 h66d9e41_16
        - ld64_osx-arm64 530 h8c8ad8c_16
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h000dee7_1
        - libcxx 11.0.0 h439d374_0
        - libiconv 1.16 haf1e3a3_0
        - libllvm11 11.0.0 hf85e3d2_0
        - libtool 2.4.6 h2e338ed_1006
        - llvm-tools 11.0.0 hf85e3d2_0
        - make 4.3 h22f3db7_1
        - pkg-config 0.29.2 h31203cd_1008
        - tapi 1100.0.11 h9ce4665_0
        - zlib 1.2.11 h7795811_1010
    run: []
test:
    commands:
        - test -f ${PREFIX}/lib/libpixman-1.a
about:
    description: 'Pixman is a low-level software library for pixel manipulation, providing

        features such as image compositing and trapezoid rasterization.

        '
    dev_url: https://cgit.freedesktop.org/pixman/
    home: http://www.pixman.org/
    license: MIT
    license_file: COPYING
    summary: A low-level software library for pixel manipulation.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - ocefpaf
        - sdvillal
