# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Oct 14 16:45:53 2021
# ------------------------------------------------

package:
  name: jasper
  version: 2.0.33
source:
  sha256: 28d28290cc2eaf70c8756d391ed8bcc8ab809a895b9a67ea6e89da23a611801a
  url: https://github.com/jasper-software/jasper/releases/download/version-2.0.33/jasper-2.0.33.tar.gz
build:
  missing_dso_whitelist:
    - /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT
  number: '0'
  run_exports:
    - jasper >=2.0.33,<3.0a0
  string: hba35424_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.17.2 h0d85af4_0
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 949.0.1 h6407bdd_23
    - cctools_osx-arm64 949.0.1 h55de48a_23
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_3
    - clangxx 11.1.0 default_he082bbe_1
    - cmake 3.21.3 hdbd2f3e_0
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - expat 2.4.1 he49afe7_0
    - krb5 1.19.2 h289aae4_2
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h6a69015_3
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcurl 7.79.1 h97da3c1_1
    - libcxx 12.0.1 habf9029_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_2
    - libnghttp2 1.43.0 hfd382f3_1
    - libssh2 1.10.0 hd3787cc_2
    - libuv 1.42.0 h0d85af4_0
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 11.1.0 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - make 4.3 h22f3db7_1
    - ncurses 6.2 h2e338ed_4
    - openssl 3.0.0 h0d85af4_1
    - rhash 1.4.1 h35c211d_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.11 h5dbffcc_1
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
    - zstd 1.5.0 h582d3a0_0
  host:
    - jpeg 9d h27ca646_0
  run:
    - jpeg >=9d,<10a
    - jpeg >=9d,<10a
test:
  commands:
    - jasper --version
about:
  home: http://www.ece.uvic.ca/~frodo/jasper/
  license: JasPer 2.0
  license_file: LICENSE
  summary: A reference implementation of the codec specified in the JPEG-2000 Part-1
    standard.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - akrherz
    - jakirkham
    - jhamman
    - ocefpaf
    - seanyen
