CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
build_platform: osx-64
c_compiler: clang
c_compiler_version: '11'
channel_sources: conda-forge/label/rust_dev,conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cross_target_platform: osx-arm64
cxx_compiler: clangxx
cxx_compiler_version: '11'
extend_keys:
- ignore_version
- ignore_build_only_deps
- pin_run_as_build
- extend_keys
fortran_compiler: gfortran
gfortran_version: 11.0.1
gmp: '6'
ignore_build_only_deps:
- python
- numpy
isl: '0.22'
libiconv: '1.16'
lua: '5'
macos_machine: arm64-apple-darwin20.0.0
mpfr: '4'
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  gmp:
    max_pin: x
  isl:
    max_pin: x.x
  libiconv:
    max_pin: x.x
  mpfr:
    max_pin: x
  zlib:
    max_pin: x.x
python: '3.9'
r_base: '3.5'
target_platform: osx-arm64
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
- - cross_target_platform
  - macos_machine
zlib: '1.2'
