# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Nov  3 01:01:31 2020
# ------------------------------------------------

package:
    name: graphite2
    version: 1.3.13
source:
    patches: null
    sha256: dd63e169b0d3cf954b397c122551ab9343e0696fb2045e1b326db0202d875f06
    url: https://github.com/silnrsi/graphite/releases/download/1.3.13/graphite2-1.3.13.tgz
build:
    detect_binary_files_with_prefix: true
    number: '1001'
    string: h9f76cd9_1001
requirements:
    build:
        - bzip2 1.0.8 haf1e3a3_3
        - c-ares 1.16.1 haf1e3a3_3
        - ca-certificates 2020.6.20 hecda079_0
        - cctools_osx-arm64 949.0.1 h1c9b417_16
        - clang 11.0.0 1
        - clang-11 11.0.0 default_h000dee7_1
        - clang_osx-arm64 11.0.0 h40be2b1_3
        - clangxx 11.0.0 default_hf57f61e_1
        - clangxx_osx-arm64 11.0.0 h4219d67_3
        - cmake 3.18.4 hfc1b5b8_0
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - expat 2.2.9 hb1e8313_2
        - krb5 1.17.1 h75d18d8_3
        - ld64_osx-64 530 h66d9e41_16
        - ld64_osx-arm64 530 h8c8ad8c_16
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h000dee7_1
        - libcurl 7.71.1 h9bf37e3_8
        - libcxx 11.0.0 h439d374_0
        - libedit 3.1.20191231 h0678c8f_2
        - libev 4.33 haf1e3a3_1
        - libllvm11 11.0.0 hf85e3d2_0
        - libnghttp2 1.41.0 h7580e61_2
        - libssh2 1.9.0 h8a08a2b_5
        - libuv 1.40.0 h22f3db7_0
        - llvm-tools 11.0.0 hf85e3d2_0
        - make 4.3 h22f3db7_1
        - ncurses 6.2 hb1e8313_2
        - openssl 1.1.1h haf1e3a3_0
        - rhash 1.3.6 haf1e3a3_1001
        - tapi 1100.0.11 h9ce4665_0
        - tk 8.6.10 hb0a8c7a_1
        - xz 5.2.5 haf1e3a3_1
        - zlib 1.2.11 h7795811_1010
    host:
        - libcxx 11.0.0 hc89144c_0
    run:
        - libcxx >=11.0.0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - conda inspect objects -p $PREFIX $PKG_NAME
about:
    home: http://graphite.sil.org/
    license: LGPLv2
    license_file: COPYING
    summary: A "smart font" system that handles the complexities of lesser-known languages
        of the world.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pkgw
