# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed May 25 16:43:16 2022
# ------------------------------------------------

package:
  name: pandas
  version: 1.4.2
source:
  sha256: 92bc1fc585f1463ca827b45535957815b7deb218c549b7c18402c322c7549a12
  url: https://github.com/pandas-dev/pandas/releases/download/v1.4.2/pandas-1.4.2.tar.gz
build:
  number: '2'
  script:
    - /Users/runner/miniforge3/conda-bld/pandas_1653497353791/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
      -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext"
      --global-option="-j${CPU_COUNT}" --no-use-pep517
  string: py38h6724fcd_2
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.5.18.1 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_1
    - clangxx 13.0.1 default_he082bbe_0
    - clangxx_osx-arm64 13.0.1 hdeb254d_1
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - cross-python_osx-arm64 3.8 23_cpython
    - crossenv 1.2.0 pyhd8ed1ab_7
    - cython 0.29.30 py38h1c67a95_0
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libblas 3.9.0 14_osx64_openblas
    - libcblas 3.9.0 14_osx64_openblas
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.3 hc203e6f_0
    - libffi 3.4.2 h0d85af4_5
    - libgfortran 5.0.0 9_3_0_h6c81a4c_23
    - libgfortran5 9.3.0 h6c81a4c_23
    - libiconv 1.16 haf1e3a3_0
    - liblapack 3.9.0 14_osx64_openblas
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.3 h41df66c_0
    - libopenblas 0.3.20 openmp_hb3cd9ec_0
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-openmp 14.0.3 ha654fa7_0
    - llvm-tools 13.0.1 h64f94b2_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.3 h96cf925_1
    - numpy 1.19.5 py38h5cb586d_3
    - openssl 3.0.3 hfe4f2af_0
    - popt 1.16 h7b079dc_2002
    - python 3.8.13 h66c20e1_0_cpython
    - python_abi 3.8 2_cp38
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h7841d2a_4
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.38.5 hd9f0692_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h6c3fc93_1014
    - zstd 1.5.2 ha9df2e0_1
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.5.18.1 h4653dfc_0
    - cython 0.29.30 py38h396b780_0
    - libblas 3.9.0 14_osxarm64_openblas
    - libcblas 3.9.0 14_osxarm64_openblas
    - libcxx 14.0.3 h6a5c8ee_0
    - libffi 3.4.2 h3422bc3_5
    - libgfortran 5.0.0.dev0 11_0_1_hf114ba7_23
    - libgfortran5 11.0.1.dev0 hf114ba7_23
    - liblapack 3.9.0 14_osxarm64_openblas
    - libopenblas 0.3.20 openmp_h2209c59_0
    - libzlib 1.2.11 h90dfc92_1014
    - llvm-openmp 14.0.3 hd125106_0
    - ncurses 6.3 h07bb92c_1
    - numpy 1.19.5 py38he594345_3
    - openssl 3.0.3 ha287fd2_0
    - pip 22.1.1 pyhd8ed1ab_0
    - python 3.8.13 hd3575e6_0_cpython
    - python_abi 3.8 2_cp38
    - readline 8.1 hedafd6a_0
    - setuptools 62.3.2 py38h10201cd_0
    - sqlite 3.38.5 h40dfcc0_0
    - tk 8.6.12 he1e0b03_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 h90dfc92_1014
  run:
    - libcxx >=13.0.1
    - numpy >=1.19.5,<2.0a0
    - python >=3.8,<3.9.0a0
    - python >=3.8,<3.9.0a0 *_cpython
    - python-dateutil >=2.8.1
    - python_abi 3.8.* *_cp38
    - pytz >=2020.1
test:
  commands:
    - pip check
  imports:
    - pandas
  requires:
    - pip
about:
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - TomAugspurger
    - WillAyd
    - jorisvandenbossche
    - jreback
    - msarahan
    - ocefpaf
    - simonjayhawkins
