# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: openssl
  version: 3.0.3
source:
  sha256: ee0078adcef1de5f003c62c80cc96527721609c6f3bb42b7795df31f8b558c0b
  url: http://www.openssl.org/source/openssl-3.0.3.tar.gz
build:
  no_link: lib/libcrypto.3.0.dylib
  number: 0
  run_exports:
    - openssl >=3.0.3,<4.0a0
  string: ha287fd2_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 13.0.1 h80e80bd_0
    - make 4.3 h22f3db7_1
    - perl 5.32.1 2_h0d85af4_perl5
  run:
    - ca-certificates
test:
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
about:
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man3.0/
  home: http://www.openssl.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  feedstock-name: openssl
  final: true
  recipe-maintainers:
    - carlodri
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
