# This file created by conda-build 3.21.9
# ------------------------------------------------

package:
  name: openssl
  version: 1.1.1p
source:
  sha256: bf61b62aaa66c7c7639942a94de4c9ae8280c08f17d4eac2e44644d9fc8ace6f
  url: https://www.openssl.org/source/openssl-1.1.1p.tar.gz
build:
  no_link: lib/libcrypto.1.1.dylib
  number: 0
  run_exports:
    - openssl >=1.1.1p,<1.1.2a
  string: ha287fd2_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 13.0.1 h80e80bd_2
    - make 4.3 h22f3db7_1
    - perl 5.32.1 2_h0d85af4_perl5
  run:
    - ca-certificates
test:
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
about:
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man1.1.1/
  home: http://www.openssl.org/
  license: OpenSSL
  license_family: Apache
  license_file: LICENSE
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  feedstock-name: openssl
  final: true
  recipe-maintainers:
    - carlodri
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
