# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri May  6 18:47:35 2022
# ------------------------------------------------

package:
  name: sqlite
  version: 3.38.5
source:
  patches: null
  sha256: 5af07de982ba658fd91a03170c945f99c971f6955bc79df3266544373e39869c
  url: https://www.sqlite.org/2022/sqlite-autoconf-3380500.tar.gz
build:
  number: '0'
  run_exports:
    - sqlite >=3.38.5,<4.0a0
  string: h40dfcc0_0
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_0
    - clangxx 13.0.1 default_he082bbe_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - ld64_osx-64 609 hd77a64a_10
    - ld64_osx-arm64 609 hfeae783_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.3 hc203e6f_0
    - libllvm13 13.0.1 h64f94b2_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-tools 13.0.1 h64f94b2_2
    - make 4.3 h22f3db7_1
    - openssl 3.0.3 hfe4f2af_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - libzlib 1.2.11 h90dfc92_1014
    - ncurses 6.3 h07bb92c_1
    - readline 8.1 hedafd6a_0
    - zlib 1.2.11 h90dfc92_1014
  run:
    - libzlib >=1.2.11,<1.3.0a0
    - ncurses >=6.3,<7.0a0
    - readline >=8.1,<9.0a0
    - readline >=8.1,<9.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - sqlite3 --version
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  dev_url: https://github.com/mackyle/sqlite
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  doc_url: http://www.sqlite.org/docs.html
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
