# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Dec 30 14:49:11 2020
# ------------------------------------------------

package:
    name: lame
    version: '3.100'
source:
    patches:
        - libmp3lame.patch
    sha256: ddfe36cab873794038ae2c1210557ad34857a4b6bdc515785d1da9e175b1da1e
    url: https://downloads.sourceforge.net/sourceforge/lame/lame-3.100.tar.gz
build:
    number: '1001'
    run_exports:
        - lame >=3.100,<3.101.0a0
    string: h27ca646_1001
requirements:
    build:
        - cctools_osx-arm64 949.0.1 h9541561_19
        - clang 11.0.0 h694c41f_2
        - clang-11 11.0.0 default_h9e6edd0_2
        - clang_osx-arm64 11.0.0 h40be2b1_8
        - clangxx 11.0.0 default_h9e6edd0_2
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - gnuconfig 2020.11.07 hd8ed1ab_0
        - ld64_osx-64 530 hea264c1_19
        - ld64_osx-arm64 530 ha0a8365_19
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h9e6edd0_2
        - libcxx 11.0.0 h4c3b8ed_1
        - libllvm11 11.0.0 hf85e3d2_0
        - llvm-tools 11.0.0 hf85e3d2_0
        - make 4.3 h22f3db7_1
        - tapi 1100.0.11 h9ce4665_0
        - zlib 1.2.11 h7795811_1010
    run: []
test:
    commands:
        - lame --genre-list testcase.mp3
about:
    description: 'LAME is a high quality MPEG Audio Layer III (MP3) encoder licensed
        under the LGPL.

        Today, LAME is considered the best MP3 encoder at mid-high bitrates and at
        VBR, mostly

        thanks to the dedicated work of its developers and the open source licensing
        model

        that allowed the project to tap into engineering resources from all around
        the world.

        '
    dev_url: https://svn.code.sf.net/p/lame/svn/trunk/lame/
    doc_url: http://lame.sourceforge.net/using.php
    home: https://lame.sourceforge.io/
    license: LGPL
    license_file: LICENSE
    summary: High quality MPEG Audio Layer III (MP3) encoder
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - soumith
