# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Nov 19 01:58:55 2020
# ------------------------------------------------

package:
    name: gmp
    version: 6.2.1
source:
    sha256: eae9326beb4158c386e39a356818031bd28f3124cf915f8c5b1dc4c7a36b4d7c
    url: https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2
build:
    number: '0'
    run_exports:
        - gmp >=6.2.1,<7.0a0
    string: h9f76cd9_0
requirements:
    build:
        - cctools_osx-arm64 949.0.1 h1c9b417_16
        - clang 11.0.0 h694c41f_2
        - clang-11 11.0.0 default_h9e6edd0_2
        - clang_osx-arm64 11.0.0 h40be2b1_5
        - clangxx 11.0.0 default_h9e6edd0_2
        - clangxx_osx-arm64 11.0.0 hc50fe25_5
        - compiler-rt 11.0.0 h01488ec_2
        - compiler-rt_osx-64 11.0.0 hd3c4e95_2
        - gnuconfig 2020.11.07 hd8ed1ab_0
        - ld64_osx-64 530 h66d9e41_16
        - ld64_osx-arm64 530 h8c8ad8c_16
        - ldid 2.1.2 h7660a38_2
        - libclang-cpp11 11.0.0 default_h9e6edd0_2
        - libcxx 11.0.0 h439d374_0
        - libllvm11 11.0.0 hf85e3d2_0
        - llvm-tools 11.0.0 hf85e3d2_0
        - m4 1.4.18 haf1e3a3_1001
        - make 4.3 h22f3db7_1
        - tapi 1100.0.11 h9ce4665_0
        - zlib 1.2.11 h7795811_1010
    host:
        - libcxx 11.0.0 hc89144c_0
    run:
        - libcxx >=11.0.0
test:
    commands:
        - test -f ${PREFIX}/lib/libgmp.a
        - test -f ${PREFIX}/lib/libgmp.dylib
        - test -f ${PREFIX}/lib/libgmpxx.a
        - test -f ${PREFIX}/lib/libgmpxx.dylib
    files:
        - test.c
    requires:
        - clang_osx-arm64 11.*
about:
    home: http://gmplib.org/
    license: GPL-2.0-or-later AND LGPL-3.0-or-later
    license_file: COPYING.LESSERv3
    summary: The GNU multiprecision library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - isuruf
        - jakirkham
